// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: collection/collection_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 初始化股票数据请求
// 参数: code 股票代码
type RPC_CollectionInitStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_CollectionInitStockReq) Reset() {
	*x = RPC_CollectionInitStockReq{}
	mi := &file_collection_collection_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_CollectionInitStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_CollectionInitStockReq) ProtoMessage() {}

func (x *RPC_CollectionInitStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_collection_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_CollectionInitStockReq.ProtoReflect.Descriptor instead.
func (*RPC_CollectionInitStockReq) Descriptor() ([]byte, []int) {
	return file_collection_collection_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RPC_CollectionInitStockReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 初始化股票数据响应
// 参数: code 股票代码
type RPC_CollectionInitStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_CollectionInitStockResp) Reset() {
	*x = RPC_CollectionInitStockResp{}
	mi := &file_collection_collection_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_CollectionInitStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_CollectionInitStockResp) ProtoMessage() {}

func (x *RPC_CollectionInitStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_collection_collection_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_CollectionInitStockResp.ProtoReflect.Descriptor instead.
func (*RPC_CollectionInitStockResp) Descriptor() ([]byte, []int) {
	return file_collection_collection_msg_proto_rawDescGZIP(), []int{1}
}

func (x *RPC_CollectionInitStockResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_collection_collection_msg_proto protoreflect.FileDescriptor

const file_collection_collection_msg_proto_rawDesc = "" +
	"\n" +
	"\x1fcollection/collection_msg.proto\"0\n" +
	"\x1aRPC_CollectionInitStockReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"1\n" +
	"\x1bRPC_CollectionInitStockResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04codeB\x06Z\x04.;pbb\x06proto3"

var (
	file_collection_collection_msg_proto_rawDescOnce sync.Once
	file_collection_collection_msg_proto_rawDescData []byte
)

func file_collection_collection_msg_proto_rawDescGZIP() []byte {
	file_collection_collection_msg_proto_rawDescOnce.Do(func() {
		file_collection_collection_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_collection_msg_proto_rawDesc), len(file_collection_collection_msg_proto_rawDesc)))
	})
	return file_collection_collection_msg_proto_rawDescData
}

var file_collection_collection_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_collection_collection_msg_proto_goTypes = []any{
	(*RPC_CollectionInitStockReq)(nil),  // 0: RPC_CollectionInitStockReq
	(*RPC_CollectionInitStockResp)(nil), // 1: RPC_CollectionInitStockResp
}
var file_collection_collection_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collection_collection_msg_proto_init() }
func file_collection_collection_msg_proto_init() {
	if File_collection_collection_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_collection_msg_proto_rawDesc), len(file_collection_collection_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collection_collection_msg_proto_goTypes,
		DependencyIndexes: file_collection_collection_msg_proto_depIdxs,
		MessageInfos:      file_collection_collection_msg_proto_msgTypes,
	}.Build()
	File_collection_collection_msg_proto = out.File
	file_collection_collection_msg_proto_goTypes = nil
	file_collection_collection_msg_proto_depIdxs = nil
}
