// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: collection/collection_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBCollectionItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LastUpdateTime int64                  `protobuf:"varint,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DBCollectionItem) Reset() {
	*x = DBCollectionItem{}
	mi := &file_collection_collection_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBCollectionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBCollectionItem) ProtoMessage() {}

func (x *DBCollectionItem) ProtoReflect() protoreflect.Message {
	mi := &file_collection_collection_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBCollectionItem.ProtoReflect.Descriptor instead.
func (*DBCollectionItem) Descriptor() ([]byte, []int) {
	return file_collection_collection_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBCollectionItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DBCollectionItem) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

var File_collection_collection_db_proto protoreflect.FileDescriptor

const file_collection_collection_db_proto_rawDesc = "" +
	"\n" +
	"\x1ecollection/collection_db.proto\"P\n" +
	"\x10DBCollectionItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12(\n" +
	"\x10last_update_time\x18\x02 \x01(\x03R\x0elastUpdateTimeB\x06Z\x04.;pbb\x06proto3"

var (
	file_collection_collection_db_proto_rawDescOnce sync.Once
	file_collection_collection_db_proto_rawDescData []byte
)

func file_collection_collection_db_proto_rawDescGZIP() []byte {
	file_collection_collection_db_proto_rawDescOnce.Do(func() {
		file_collection_collection_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_collection_db_proto_rawDesc), len(file_collection_collection_db_proto_rawDesc)))
	})
	return file_collection_collection_db_proto_rawDescData
}

var file_collection_collection_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_collection_collection_db_proto_goTypes = []any{
	(*DBCollectionItem)(nil), // 0: DBCollectionItem
}
var file_collection_collection_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collection_collection_db_proto_init() }
func file_collection_collection_db_proto_init() {
	if File_collection_collection_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_collection_db_proto_rawDesc), len(file_collection_collection_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collection_collection_db_proto_goTypes,
		DependencyIndexes: file_collection_collection_db_proto_depIdxs,
		MessageInfos:      file_collection_collection_db_proto_msgTypes,
	}.Build()
	File_collection_collection_db_proto = out.File
	file_collection_collection_db_proto_goTypes = nil
	file_collection_collection_db_proto_depIdxs = nil
}
