// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: collection/collection_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 初始化股票数据请求
// 参数: code 股票代码
type RPC_CollectionInitStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *RPC_CollectionInitStockReq) Reset() {
	*x = RPC_CollectionInitStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_collection_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_CollectionInitStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_CollectionInitStockReq) ProtoMessage() {}

func (x *RPC_CollectionInitStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_collection_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_CollectionInitStockReq.ProtoReflect.Descriptor instead.
func (*RPC_CollectionInitStockReq) Descriptor() ([]byte, []int) {
	return file_collection_collection_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RPC_CollectionInitStockReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 初始化股票数据响应
// 参数: code 股票代码
type RPC_CollectionInitStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *RPC_CollectionInitStockResp) Reset() {
	*x = RPC_CollectionInitStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_collection_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPC_CollectionInitStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_CollectionInitStockResp) ProtoMessage() {}

func (x *RPC_CollectionInitStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_collection_collection_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_CollectionInitStockResp.ProtoReflect.Descriptor instead.
func (*RPC_CollectionInitStockResp) Descriptor() ([]byte, []int) {
	return file_collection_collection_msg_proto_rawDescGZIP(), []int{1}
}

func (x *RPC_CollectionInitStockResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_collection_collection_msg_proto protoreflect.FileDescriptor

var file_collection_collection_msg_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x1a, 0x52, 0x50, 0x43, 0x5f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x52, 0x50, 0x43, 0x5f, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collection_collection_msg_proto_rawDescOnce sync.Once
	file_collection_collection_msg_proto_rawDescData = file_collection_collection_msg_proto_rawDesc
)

func file_collection_collection_msg_proto_rawDescGZIP() []byte {
	file_collection_collection_msg_proto_rawDescOnce.Do(func() {
		file_collection_collection_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_collection_collection_msg_proto_rawDescData)
	})
	return file_collection_collection_msg_proto_rawDescData
}

var file_collection_collection_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_collection_collection_msg_proto_goTypes = []interface{}{
	(*RPC_CollectionInitStockReq)(nil),  // 0: RPC_CollectionInitStockReq
	(*RPC_CollectionInitStockResp)(nil), // 1: RPC_CollectionInitStockResp
}
var file_collection_collection_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collection_collection_msg_proto_init() }
func file_collection_collection_msg_proto_init() {
	if File_collection_collection_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collection_collection_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_CollectionInitStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_collection_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPC_CollectionInitStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collection_collection_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collection_collection_msg_proto_goTypes,
		DependencyIndexes: file_collection_collection_msg_proto_depIdxs,
		MessageInfos:      file_collection_collection_msg_proto_msgTypes,
	}.Build()
	File_collection_collection_msg_proto = out.File
	file_collection_collection_msg_proto_rawDesc = nil
	file_collection_collection_msg_proto_goTypes = nil
	file_collection_collection_msg_proto_depIdxs = nil
}
