// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=ErrorCode" json:"Code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorData) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_Success
}

func (x *ErrorData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//集合包
type MessagePackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*SocketMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MessagePackage) Reset() {
	*x = MessagePackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePackage) ProtoMessage() {}

func (x *MessagePackage) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePackage.ProtoReflect.Descriptor instead.
func (*MessagePackage) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{1}
}

func (x *MessagePackage) GetMessages() []*SocketMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

//用户消息流结构1
type SocketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName     string     `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`         //消息名称
	ServicePath string     `protobuf:"bytes,2,opt,name=ServicePath,proto3" json:"ServicePath,omitempty"` // 消息路由地址 部分消息前端确定转发给谁 \worker\worker0
	Data        *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Sec         string     `protobuf:"bytes,4,opt,name=sec,proto3" json:"sec,omitempty"` //密文
}

func (x *SocketMessage) Reset() {
	*x = SocketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketMessage) ProtoMessage() {}

func (x *SocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketMessage.ProtoReflect.Descriptor instead.
func (*SocketMessage) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{2}
}

func (x *SocketMessage) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *SocketMessage) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *SocketMessage) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SocketMessage) GetSec() string {
	if x != nil {
		return x.Sec
	}
	return ""
}

//网关Http 路由请求
type Rpc_GatewayHttpRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Meta    string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Message []byte `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Rpc_GatewayHttpRouteReq) Reset() {
	*x = Rpc_GatewayHttpRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayHttpRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteReq) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{3}
}

func (x *Rpc_GatewayHttpRouteReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteReq) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Rpc_GatewayHttpRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Body        []byte `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *Rpc_GatewayHttpRouteResp) Reset() {
	*x = Rpc_GatewayHttpRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayHttpRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteResp) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{4}
}

func (x *Rpc_GatewayHttpRouteResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Rpc_GatewaySocketRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string     `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Meta    string     `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Message *anypb.Any `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Rpc_GatewaySocketRouteReq) Reset() {
	*x = Rpc_GatewaySocketRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySocketRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySocketRouteReq) ProtoMessage() {}

func (x *Rpc_GatewaySocketRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySocketRouteReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySocketRouteReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{5}
}

func (x *Rpc_GatewaySocketRouteReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewaySocketRouteReq) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *Rpc_GatewaySocketRouteReq) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

type Rpc_GatewaySocketRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicePath string           `protobuf:"bytes,1,opt,name=ServicePath,proto3" json:"ServicePath,omitempty"`
	ChangeMeta  string           `protobuf:"bytes,2,opt,name=ChangeMeta,proto3" json:"ChangeMeta,omitempty"`
	Reply       []*SocketMessage `protobuf:"bytes,3,rep,name=Reply,proto3" json:"Reply,omitempty"`
	ErrorData   *ErrorData       `protobuf:"bytes,4,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"`
}

func (x *Rpc_GatewaySocketRouteResp) Reset() {
	*x = Rpc_GatewaySocketRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySocketRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySocketRouteResp) ProtoMessage() {}

func (x *Rpc_GatewaySocketRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySocketRouteResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySocketRouteResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{6}
}

func (x *Rpc_GatewaySocketRouteResp) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *Rpc_GatewaySocketRouteResp) GetChangeMeta() string {
	if x != nil {
		return x.ChangeMeta
	}
	return ""
}

func (x *Rpc_GatewaySocketRouteResp) GetReply() []*SocketMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *Rpc_GatewaySocketRouteResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

// RPC向用户代理发送消息
type Rpc_GatewaySendMsgToAgentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionId string           `protobuf:"bytes,1,opt,name=UserSessionId,proto3" json:"UserSessionId,omitempty"` //用户会话ID
	Reply         []*SocketMessage `protobuf:"bytes,2,rep,name=Reply,proto3" json:"Reply,omitempty"`                 //回复消息
}

func (x *Rpc_GatewaySendMsgToAgentReq) Reset() {
	*x = Rpc_GatewaySendMsgToAgentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgToAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgToAgentReq) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgToAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgToAgentReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgToAgentReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{7}
}

func (x *Rpc_GatewaySendMsgToAgentReq) GetUserSessionId() string {
	if x != nil {
		return x.UserSessionId
	}
	return ""
}

func (x *Rpc_GatewaySendMsgToAgentReq) GetReply() []*SocketMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

type Rpc_GatewaySendMsgToAgentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"` //错误信息
}

func (x *Rpc_GatewaySendMsgToAgentResp) Reset() {
	*x = Rpc_GatewaySendMsgToAgentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgToAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgToAgentResp) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgToAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgToAgentResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgToAgentResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{8}
}

func (x *Rpc_GatewaySendMsgToAgentResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

type Rpc_GatewaySendMsgsToAgentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionIds []string         `protobuf:"bytes,1,rep,name=UserSessionIds,proto3" json:"UserSessionIds,omitempty"` //用户会话ID列表
	Reply          []*SocketMessage `protobuf:"bytes,2,rep,name=Reply,proto3" json:"Reply,omitempty"`                   //回复消息
}

func (x *Rpc_GatewaySendMsgsToAgentsReq) Reset() {
	*x = Rpc_GatewaySendMsgsToAgentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgsToAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgsToAgentsReq) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgsToAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgsToAgentsReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgsToAgentsReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{9}
}

func (x *Rpc_GatewaySendMsgsToAgentsReq) GetUserSessionIds() []string {
	if x != nil {
		return x.UserSessionIds
	}
	return nil
}

func (x *Rpc_GatewaySendMsgsToAgentsReq) GetReply() []*SocketMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

type Rpc_GatewaySendMsgsToAgentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"` //错误信息
}

func (x *Rpc_GatewaySendMsgsToAgentsResp) Reset() {
	*x = Rpc_GatewaySendMsgsToAgentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgsToAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgsToAgentsResp) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgsToAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgsToAgentsResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgsToAgentsResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{10}
}

func (x *Rpc_GatewaySendMsgsToAgentsResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

type Rpc_GatewaySendMsgsToAllAgentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply []*SocketMessage `protobuf:"bytes,2,rep,name=Reply,proto3" json:"Reply,omitempty"` //回复消息
}

func (x *Rpc_GatewaySendMsgsToAllAgentsReq) Reset() {
	*x = Rpc_GatewaySendMsgsToAllAgentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgsToAllAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgsToAllAgentsReq) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgsToAllAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgsToAllAgentsReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgsToAllAgentsReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{11}
}

func (x *Rpc_GatewaySendMsgsToAllAgentsReq) GetReply() []*SocketMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

type Rpc_GatewaySendMsgsToAllAgentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"` //错误信息
}

func (x *Rpc_GatewaySendMsgsToAllAgentsResp) Reset() {
	*x = Rpc_GatewaySendMsgsToAllAgentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewaySendMsgsToAllAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewaySendMsgsToAllAgentsResp) ProtoMessage() {}

func (x *Rpc_GatewaySendMsgsToAllAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewaySendMsgsToAllAgentsResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewaySendMsgsToAllAgentsResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{12}
}

func (x *Rpc_GatewaySendMsgsToAllAgentsResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

type Rpc_GatewayCloseAgentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionIds []string `protobuf:"bytes,1,rep,name=UserSessionIds,proto3" json:"UserSessionIds,omitempty"` //用户会话ID列表
}

func (x *Rpc_GatewayCloseAgentsReq) Reset() {
	*x = Rpc_GatewayCloseAgentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayCloseAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayCloseAgentsReq) ProtoMessage() {}

func (x *Rpc_GatewayCloseAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayCloseAgentsReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayCloseAgentsReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{13}
}

func (x *Rpc_GatewayCloseAgentsReq) GetUserSessionIds() []string {
	if x != nil {
		return x.UserSessionIds
	}
	return nil
}

type Rpc_GatewayCloseAgentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorData *ErrorData `protobuf:"bytes,1,opt,name=ErrorData,proto3" json:"ErrorData,omitempty"` //错误信息
}

func (x *Rpc_GatewayCloseAgentsResp) Reset() {
	*x = Rpc_GatewayCloseAgentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rpc_GatewayCloseAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayCloseAgentsResp) ProtoMessage() {}

func (x *Rpc_GatewayCloseAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayCloseAgentsResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayCloseAgentsResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{14}
}

func (x *Rpc_GatewayCloseAgentsResp) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

var File_comm_proto protoreflect.FileDescriptor

var file_comm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x3c, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x2a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x87, 0x01,
	0x0a, 0x0d, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x63, 0x22, 0x61, 0x0a, 0x17, 0x52, 0x70, 0x63, 0x5f, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x18, 0x52, 0x70,
	0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x79, 0x0a, 0x19,
	0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x1a, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x1c, 0x52, 0x70, 0x63, 0x5f,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x49, 0x0a, 0x1d, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x6e, 0x0a, 0x1e, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x73, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x26, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x4b, 0x0a, 0x1f, 0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x73, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x49, 0x0a, 0x21,
	0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x73, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4e, 0x0a, 0x22, 0x52, 0x70, 0x63, 0x5f, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x73, 0x54, 0x6f,
	0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x19, 0x52, 0x70, 0x63, 0x5f, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x46, 0x0a, 0x1a,
	0x52, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_proto_rawDescOnce sync.Once
	file_comm_proto_rawDescData = file_comm_proto_rawDesc
)

func file_comm_proto_rawDescGZIP() []byte {
	file_comm_proto_rawDescOnce.Do(func() {
		file_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_proto_rawDescData)
	})
	return file_comm_proto_rawDescData
}

var file_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_comm_proto_goTypes = []interface{}{
	(*ErrorData)(nil),                          // 0: ErrorData
	(*MessagePackage)(nil),                     // 1: MessagePackage
	(*SocketMessage)(nil),                      // 2: SocketMessage
	(*Rpc_GatewayHttpRouteReq)(nil),            // 3: Rpc_GatewayHttpRouteReq
	(*Rpc_GatewayHttpRouteResp)(nil),           // 4: Rpc_GatewayHttpRouteResp
	(*Rpc_GatewaySocketRouteReq)(nil),          // 5: Rpc_GatewaySocketRouteReq
	(*Rpc_GatewaySocketRouteResp)(nil),         // 6: Rpc_GatewaySocketRouteResp
	(*Rpc_GatewaySendMsgToAgentReq)(nil),       // 7: Rpc_GatewaySendMsgToAgentReq
	(*Rpc_GatewaySendMsgToAgentResp)(nil),      // 8: Rpc_GatewaySendMsgToAgentResp
	(*Rpc_GatewaySendMsgsToAgentsReq)(nil),     // 9: Rpc_GatewaySendMsgsToAgentsReq
	(*Rpc_GatewaySendMsgsToAgentsResp)(nil),    // 10: Rpc_GatewaySendMsgsToAgentsResp
	(*Rpc_GatewaySendMsgsToAllAgentsReq)(nil),  // 11: Rpc_GatewaySendMsgsToAllAgentsReq
	(*Rpc_GatewaySendMsgsToAllAgentsResp)(nil), // 12: Rpc_GatewaySendMsgsToAllAgentsResp
	(*Rpc_GatewayCloseAgentsReq)(nil),          // 13: Rpc_GatewayCloseAgentsReq
	(*Rpc_GatewayCloseAgentsResp)(nil),         // 14: Rpc_GatewayCloseAgentsResp
	(ErrorCode)(0),                             // 15: ErrorCode
	(*anypb.Any)(nil),                          // 16: google.protobuf.Any
}
var file_comm_proto_depIdxs = []int32{
	15, // 0: ErrorData.Code:type_name -> ErrorCode
	2,  // 1: MessagePackage.messages:type_name -> SocketMessage
	16, // 2: SocketMessage.data:type_name -> google.protobuf.Any
	16, // 3: Rpc_GatewaySocketRouteReq.Message:type_name -> google.protobuf.Any
	2,  // 4: Rpc_GatewaySocketRouteResp.Reply:type_name -> SocketMessage
	0,  // 5: Rpc_GatewaySocketRouteResp.ErrorData:type_name -> ErrorData
	2,  // 6: Rpc_GatewaySendMsgToAgentReq.Reply:type_name -> SocketMessage
	0,  // 7: Rpc_GatewaySendMsgToAgentResp.ErrorData:type_name -> ErrorData
	2,  // 8: Rpc_GatewaySendMsgsToAgentsReq.Reply:type_name -> SocketMessage
	0,  // 9: Rpc_GatewaySendMsgsToAgentsResp.ErrorData:type_name -> ErrorData
	2,  // 10: Rpc_GatewaySendMsgsToAllAgentsReq.Reply:type_name -> SocketMessage
	0,  // 11: Rpc_GatewaySendMsgsToAllAgentsResp.ErrorData:type_name -> ErrorData
	0,  // 12: Rpc_GatewayCloseAgentsResp.ErrorData:type_name -> ErrorData
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_comm_proto_init() }
func file_comm_proto_init() {
	if File_comm_proto != nil {
		return
	}
	file_errorcode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayHttpRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayHttpRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySocketRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySocketRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgToAgentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgToAgentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgsToAgentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgsToAgentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgsToAllAgentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewaySendMsgsToAllAgentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayCloseAgentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rpc_GatewayCloseAgentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_proto_goTypes,
		DependencyIndexes: file_comm_proto_depIdxs,
		MessageInfos:      file_comm_proto_msgTypes,
	}.Build()
	File_comm_proto = out.File
	file_comm_proto_rawDesc = nil
	file_comm_proto_goTypes = nil
	file_comm_proto_depIdxs = nil
}
