// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: company/company_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 公司基本信息
type Company struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`                            //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 公司id
	Symbol          string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_market_symbol"`                    //@go_tags(`gorm:"symbol;uniqueIndex:uk_market_symbol" json:"symbol"`) 股票代码
	Name            string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"name" gorm:"name"`                        //@go_tags(`gorm:"name" json:"name"`) 公司简称
	FullName        string                 `protobuf:"bytes,4,opt,name=FullName,proto3" json:"full_name" gorm:"full_name"`                //@go_tags(`gorm:"full_name" json:"full_name"`) 公司全称
	Market          string                 `protobuf:"bytes,5,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_market_symbol"`                    //@go_tags(`gorm:"market;uniqueIndex:uk_market_symbol" json:"market"`) 市场标识(sh/sz等)
	Exchange        string                 `protobuf:"bytes,6,opt,name=Exchange,proto3" json:"exchange" gorm:"exchange"`                //@go_tags(`gorm:"exchange" json:"exchange"`) 交易所(SSE/SZSE等)
	ISIN            string                 `protobuf:"bytes,7,opt,name=ISIN,proto3" json:"isin" gorm:"isin;index"`                        //@go_tags(`gorm:"isin;index" json:"isin"`) 国际证券识别码
	Industry        string                 `protobuf:"bytes,8,opt,name=Industry,proto3" json:"industry" gorm:"industry"`                //@go_tags(`gorm:"industry" json:"industry"`) 行业
	Sector          string                 `protobuf:"bytes,9,opt,name=Sector,proto3" json:"sector" gorm:"sector"`                    //@go_tags(`gorm:"sector" json:"sector"`) 板块
	Area            string                 `protobuf:"bytes,10,opt,name=Area,proto3" json:"area" gorm:"area"`                       //@go_tags(`gorm:"area" json:"area"`) 地区
	ListDate        string                 `protobuf:"bytes,11,opt,name=ListDate,proto3" json:"list_date" gorm:"list_date"`               //@go_tags(`gorm:"list_date" json:"list_date"`) 上市日期(YYYYMMDD)
	Status          string                 `protobuf:"bytes,12,opt,name=Status,proto3" json:"status" gorm:"status"`                   //@go_tags(`gorm:"status" json:"status"`) 上市状态
	Website         string                 `protobuf:"bytes,13,opt,name=Website,proto3" json:"website" gorm:"website"`                 //@go_tags(`gorm:"website" json:"website"`) 官网地址
	Address         string                 `protobuf:"bytes,14,opt,name=Address,proto3" json:"address" gorm:"address"`                 //@go_tags(`gorm:"address" json:"address"`) 注册地址
	Description     string                 `protobuf:"bytes,15,opt,name=Description,proto3" json:"description" gorm:"description"`         //@go_tags(`gorm:"description" json:"description"`) 公司简介
	LegalPerson     string                 `protobuf:"bytes,16,opt,name=LegalPerson,proto3" json:"legal_person" gorm:"legal_person"`         //@go_tags(`gorm:"legal_person" json:"legal_person"`) 法定代表人
	Currency        string                 `protobuf:"bytes,17,opt,name=Currency,proto3" json:"currency" gorm:"currency"`               //@go_tags(`gorm:"currency" json:"currency"`) 币种
	Employees       int64                  `protobuf:"varint,18,opt,name=Employees,proto3" json:"employees" gorm:"employees"`            //@go_tags(`gorm:"employees" json:"employees"`) 员工数量
	ParentCompanyId string                 `protobuf:"bytes,19,opt,name=ParentCompanyId,proto3" json:"parent_company_id" gorm:"parent_company_id"` //@go_tags(`gorm:"parent_company_id" json:"parent_company_id"`) 母公司id
	Aliases         []string               `protobuf:"bytes,20,rep,name=Aliases,proto3" json:"aliases" gorm:"aliases;serializer:json"`                 //@go_tags(`gorm:"aliases;serializer:json" json:"aliases"`) 公司别名列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_company_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_company_db_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Company) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Company) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Company) GetISIN() string {
	if x != nil {
		return x.ISIN
	}
	return ""
}

func (x *Company) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *Company) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Company) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Company) GetListDate() string {
	if x != nil {
		return x.ListDate
	}
	return ""
}

func (x *Company) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Company) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Company) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Company) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Company) GetLegalPerson() string {
	if x != nil {
		return x.LegalPerson
	}
	return ""
}

func (x *Company) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Company) GetEmployees() int64 {
	if x != nil {
		return x.Employees
	}
	return 0
}

func (x *Company) GetParentCompanyId() string {
	if x != nil {
		return x.ParentCompanyId
	}
	return ""
}

func (x *Company) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// 公司财务信息
type CompanyFinance struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`                                      //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 记录id
	CompanyId           string                 `protobuf:"bytes,2,opt,name=CompanyId,proto3" json:"company_id" gorm:"company_id;index:idx_company_period"`                        //@go_tags(`gorm:"company_id;index:idx_company_period" json:"company_id"`) 公司id
	Period              string                 `protobuf:"bytes,3,opt,name=Period,proto3" json:"period" gorm:"period;index:idx_company_period"`                              //@go_tags(`gorm:"period;index:idx_company_period" json:"period"`) 报告期(YYYYMMDD/YYYYQn)
	Source              string                 `protobuf:"bytes,4,opt,name=Source,proto3" json:"source" gorm:"source"`                              //@go_tags(`gorm:"source" json:"source"`) 数据来源
	Currency            string                 `protobuf:"bytes,5,opt,name=Currency,proto3" json:"currency" gorm:"currency"`                          //@go_tags(`gorm:"currency" json:"currency"`) 币种
	MarketCap           float64                `protobuf:"fixed64,6,opt,name=MarketCap,proto3" json:"market_cap" gorm:"market_cap"`                      //@go_tags(`gorm:"market_cap" json:"market_cap"`) 总市值
	EV                  float64                `protobuf:"fixed64,7,opt,name=EV,proto3" json:"ev" gorm:"ev"`                                    //@go_tags(`gorm:"ev" json:"ev"`) 企业价值
	PE                  float64                `protobuf:"fixed64,8,opt,name=PE,proto3" json:"pe" gorm:"pe"`                                    //@go_tags(`gorm:"pe" json:"pe"`) 市盈率
	PB                  float64                `protobuf:"fixed64,9,opt,name=PB,proto3" json:"pb" gorm:"pb"`                                    //@go_tags(`gorm:"pb" json:"pb"`) 市净率
	PS                  float64                `protobuf:"fixed64,10,opt,name=PS,proto3" json:"ps" gorm:"ps"`                                   //@go_tags(`gorm:"ps" json:"ps"`) 市销率
	DividendYield       float64                `protobuf:"fixed64,11,opt,name=DividendYield,proto3" json:"dividend_yield" gorm:"dividend_yield"`             //@go_tags(`gorm:"dividend_yield" json:"dividend_yield"`) 股息率(%)
	ROE                 float64                `protobuf:"fixed64,12,opt,name=ROE,proto3" json:"roe" gorm:"roe"`                                 //@go_tags(`gorm:"roe" json:"roe"`) 净资产收益率(%)
	ROA                 float64                `protobuf:"fixed64,13,opt,name=ROA,proto3" json:"roa" gorm:"roa"`                                 //@go_tags(`gorm:"roa" json:"roa"`) 资产收益率(%)
	GrossMargin         float64                `protobuf:"fixed64,14,opt,name=GrossMargin,proto3" json:"gross_margin" gorm:"gross_margin"`                 //@go_tags(`gorm:"gross_margin" json:"gross_margin"`) 毛利率(%)
	OperatingMargin     float64                `protobuf:"fixed64,15,opt,name=OperatingMargin,proto3" json:"operating_margin" gorm:"operating_margin"`         //@go_tags(`gorm:"operating_margin" json:"operating_margin"`) 营业利润率(%)
	NetMargin           float64                `protobuf:"fixed64,16,opt,name=NetMargin,proto3" json:"net_margin" gorm:"net_margin"`                     //@go_tags(`gorm:"net_margin" json:"net_margin"`) 净利率(%)
	EPS                 float64                `protobuf:"fixed64,17,opt,name=EPS,proto3" json:"eps" gorm:"eps"`                                 //@go_tags(`gorm:"eps" json:"eps"`) 每股收益
	BPS                 float64                `protobuf:"fixed64,18,opt,name=BPS,proto3" json:"bps" gorm:"bps"`                                 //@go_tags(`gorm:"bps" json:"bps"`) 每股净资产
	Revenue             float64                `protobuf:"fixed64,19,opt,name=Revenue,proto3" json:"revenue" gorm:"revenue"`                         //@go_tags(`gorm:"revenue" json:"revenue"`) 营业收入
	NetIncome           float64                `protobuf:"fixed64,20,opt,name=NetIncome,proto3" json:"net_income" gorm:"net_income"`                     //@go_tags(`gorm:"net_income" json:"net_income"`) 净利润
	EBITDA              float64                `protobuf:"fixed64,21,opt,name=EBITDA,proto3" json:"ebitda" gorm:"ebitda"`                           //@go_tags(`gorm:"ebitda" json:"ebitda"`) EBITDA
	EBIT                float64                `protobuf:"fixed64,22,opt,name=EBIT,proto3" json:"ebit" gorm:"ebit"`                               //@go_tags(`gorm:"ebit" json:"ebit"`) EBIT
	OperatingCashFlow   float64                `protobuf:"fixed64,23,opt,name=OperatingCashFlow,proto3" json:"operating_cash_flow" gorm:"operating_cash_flow"`     //@go_tags(`gorm:"operating_cash_flow" json:"operating_cash_flow"`) 经营现金流
	FreeCashFlow        float64                `protobuf:"fixed64,24,opt,name=FreeCashFlow,proto3" json:"free_cash_flow" gorm:"free_cash_flow"`               //@go_tags(`gorm:"free_cash_flow" json:"free_cash_flow"`) 自由现金流
	CAPEX               float64                `protobuf:"fixed64,25,opt,name=CAPEX,proto3" json:"capex" gorm:"capex"`                             //@go_tags(`gorm:"capex" json:"capex"`) 资本开支
	TotalAssets         float64                `protobuf:"fixed64,26,opt,name=TotalAssets,proto3" json:"total_assets" gorm:"total_assets"`                 //@go_tags(`gorm:"total_assets" json:"total_assets"`) 资产总计
	TotalLiabilities    float64                `protobuf:"fixed64,27,opt,name=TotalLiabilities,proto3" json:"total_liabilities" gorm:"total_liabilities"`       //@go_tags(`gorm:"total_liabilities" json:"total_liabilities"`) 负债总计
	ShareholderEquity   float64                `protobuf:"fixed64,28,opt,name=ShareholderEquity,proto3" json:"shareholder_equity" gorm:"shareholder_equity"`     //@go_tags(`gorm:"shareholder_equity" json:"shareholder_equity"`) 股东权益
	DebtToEquity        float64                `protobuf:"fixed64,29,opt,name=DebtToEquity,proto3" json:"debt_to_equity" gorm:"debt_to_equity"`               //@go_tags(`gorm:"debt_to_equity" json:"debt_to_equity"`) 负债/权益
	AssetLiabilityRatio float64                `protobuf:"fixed64,30,opt,name=AssetLiabilityRatio,proto3" json:"asset_liability_ratio" gorm:"asset_liability_ratio"` //@go_tags(`gorm:"asset_liability_ratio" json:"asset_liability_ratio"`) 资产负债率(%)
	CurrentRatio        float64                `protobuf:"fixed64,31,opt,name=CurrentRatio,proto3" json:"current_ratio" gorm:"current_ratio"`               //@go_tags(`gorm:"current_ratio" json:"current_ratio"`) 流动比率
	QuickRatio          float64                `protobuf:"fixed64,32,opt,name=QuickRatio,proto3" json:"quick_ratio" gorm:"quick_ratio"`                   //@go_tags(`gorm:"quick_ratio" json:"quick_ratio"`) 速动比率
	InterestCoverage    float64                `protobuf:"fixed64,33,opt,name=InterestCoverage,proto3" json:"interest_coverage" gorm:"interest_coverage"`       //@go_tags(`gorm:"interest_coverage" json:"interest_coverage"`) 利息保障倍数
	CashAndEquivalents  float64                `protobuf:"fixed64,34,opt,name=CashAndEquivalents,proto3" json:"cash_and_equivalents" gorm:"cash_and_equivalents"`   //@go_tags(`gorm:"cash_and_equivalents" json:"cash_and_equivalents"`) 货币资金
	SharesOutstanding   int64                  `protobuf:"varint,35,opt,name=SharesOutstanding,proto3" json:"shares_outstanding" gorm:"shares_outstanding"`      //@go_tags(`gorm:"shares_outstanding" json:"shares_outstanding"`) 流通股本
	UpdatedAt           int64                  `protobuf:"varint,36,opt,name=UpdatedAt,proto3" json:"updated_at" gorm:"updated_at"`                      //@go_tags(`gorm:"updated_at" json:"updated_at"`) 更新时间(Unix秒)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompanyFinance) Reset() {
	*x = CompanyFinance{}
	mi := &file_company_company_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyFinance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyFinance) ProtoMessage() {}

func (x *CompanyFinance) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyFinance.ProtoReflect.Descriptor instead.
func (*CompanyFinance) Descriptor() ([]byte, []int) {
	return file_company_company_db_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyFinance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyFinance) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CompanyFinance) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *CompanyFinance) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompanyFinance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CompanyFinance) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *CompanyFinance) GetEV() float64 {
	if x != nil {
		return x.EV
	}
	return 0
}

func (x *CompanyFinance) GetPE() float64 {
	if x != nil {
		return x.PE
	}
	return 0
}

func (x *CompanyFinance) GetPB() float64 {
	if x != nil {
		return x.PB
	}
	return 0
}

func (x *CompanyFinance) GetPS() float64 {
	if x != nil {
		return x.PS
	}
	return 0
}

func (x *CompanyFinance) GetDividendYield() float64 {
	if x != nil {
		return x.DividendYield
	}
	return 0
}

func (x *CompanyFinance) GetROE() float64 {
	if x != nil {
		return x.ROE
	}
	return 0
}

func (x *CompanyFinance) GetROA() float64 {
	if x != nil {
		return x.ROA
	}
	return 0
}

func (x *CompanyFinance) GetGrossMargin() float64 {
	if x != nil {
		return x.GrossMargin
	}
	return 0
}

func (x *CompanyFinance) GetOperatingMargin() float64 {
	if x != nil {
		return x.OperatingMargin
	}
	return 0
}

func (x *CompanyFinance) GetNetMargin() float64 {
	if x != nil {
		return x.NetMargin
	}
	return 0
}

func (x *CompanyFinance) GetEPS() float64 {
	if x != nil {
		return x.EPS
	}
	return 0
}

func (x *CompanyFinance) GetBPS() float64 {
	if x != nil {
		return x.BPS
	}
	return 0
}

func (x *CompanyFinance) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *CompanyFinance) GetNetIncome() float64 {
	if x != nil {
		return x.NetIncome
	}
	return 0
}

func (x *CompanyFinance) GetEBITDA() float64 {
	if x != nil {
		return x.EBITDA
	}
	return 0
}

func (x *CompanyFinance) GetEBIT() float64 {
	if x != nil {
		return x.EBIT
	}
	return 0
}

func (x *CompanyFinance) GetOperatingCashFlow() float64 {
	if x != nil {
		return x.OperatingCashFlow
	}
	return 0
}

func (x *CompanyFinance) GetFreeCashFlow() float64 {
	if x != nil {
		return x.FreeCashFlow
	}
	return 0
}

func (x *CompanyFinance) GetCAPEX() float64 {
	if x != nil {
		return x.CAPEX
	}
	return 0
}

func (x *CompanyFinance) GetTotalAssets() float64 {
	if x != nil {
		return x.TotalAssets
	}
	return 0
}

func (x *CompanyFinance) GetTotalLiabilities() float64 {
	if x != nil {
		return x.TotalLiabilities
	}
	return 0
}

func (x *CompanyFinance) GetShareholderEquity() float64 {
	if x != nil {
		return x.ShareholderEquity
	}
	return 0
}

func (x *CompanyFinance) GetDebtToEquity() float64 {
	if x != nil {
		return x.DebtToEquity
	}
	return 0
}

func (x *CompanyFinance) GetAssetLiabilityRatio() float64 {
	if x != nil {
		return x.AssetLiabilityRatio
	}
	return 0
}

func (x *CompanyFinance) GetCurrentRatio() float64 {
	if x != nil {
		return x.CurrentRatio
	}
	return 0
}

func (x *CompanyFinance) GetQuickRatio() float64 {
	if x != nil {
		return x.QuickRatio
	}
	return 0
}

func (x *CompanyFinance) GetInterestCoverage() float64 {
	if x != nil {
		return x.InterestCoverage
	}
	return 0
}

func (x *CompanyFinance) GetCashAndEquivalents() float64 {
	if x != nil {
		return x.CashAndEquivalents
	}
	return 0
}

func (x *CompanyFinance) GetSharesOutstanding() int64 {
	if x != nil {
		return x.SharesOutstanding
	}
	return 0
}

func (x *CompanyFinance) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_company_company_db_proto protoreflect.FileDescriptor

const file_company_company_db_proto_rawDesc = "" +
	"\n" +
	"\x18company/company_db.proto\"\x9b\x04\n" +
	"\aCompany\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFullName\x18\x04 \x01(\tR\bFullName\x12\x16\n" +
	"\x06Market\x18\x05 \x01(\tR\x06Market\x12\x1a\n" +
	"\bExchange\x18\x06 \x01(\tR\bExchange\x12\x12\n" +
	"\x04ISIN\x18\a \x01(\tR\x04ISIN\x12\x1a\n" +
	"\bIndustry\x18\b \x01(\tR\bIndustry\x12\x16\n" +
	"\x06Sector\x18\t \x01(\tR\x06Sector\x12\x12\n" +
	"\x04Area\x18\n" +
	" \x01(\tR\x04Area\x12\x1a\n" +
	"\bListDate\x18\v \x01(\tR\bListDate\x12\x16\n" +
	"\x06Status\x18\f \x01(\tR\x06Status\x12\x18\n" +
	"\aWebsite\x18\r \x01(\tR\aWebsite\x12\x18\n" +
	"\aAddress\x18\x0e \x01(\tR\aAddress\x12 \n" +
	"\vDescription\x18\x0f \x01(\tR\vDescription\x12 \n" +
	"\vLegalPerson\x18\x10 \x01(\tR\vLegalPerson\x12\x1a\n" +
	"\bCurrency\x18\x11 \x01(\tR\bCurrency\x12\x1c\n" +
	"\tEmployees\x18\x12 \x01(\x03R\tEmployees\x12(\n" +
	"\x0fParentCompanyId\x18\x13 \x01(\tR\x0fParentCompanyId\x12\x18\n" +
	"\aAliases\x18\x14 \x03(\tR\aAliases\"\xca\b\n" +
	"\x0eCompanyFinance\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1c\n" +
	"\tCompanyId\x18\x02 \x01(\tR\tCompanyId\x12\x16\n" +
	"\x06Period\x18\x03 \x01(\tR\x06Period\x12\x16\n" +
	"\x06Source\x18\x04 \x01(\tR\x06Source\x12\x1a\n" +
	"\bCurrency\x18\x05 \x01(\tR\bCurrency\x12\x1c\n" +
	"\tMarketCap\x18\x06 \x01(\x01R\tMarketCap\x12\x0e\n" +
	"\x02EV\x18\a \x01(\x01R\x02EV\x12\x0e\n" +
	"\x02PE\x18\b \x01(\x01R\x02PE\x12\x0e\n" +
	"\x02PB\x18\t \x01(\x01R\x02PB\x12\x0e\n" +
	"\x02PS\x18\n" +
	" \x01(\x01R\x02PS\x12$\n" +
	"\rDividendYield\x18\v \x01(\x01R\rDividendYield\x12\x10\n" +
	"\x03ROE\x18\f \x01(\x01R\x03ROE\x12\x10\n" +
	"\x03ROA\x18\r \x01(\x01R\x03ROA\x12 \n" +
	"\vGrossMargin\x18\x0e \x01(\x01R\vGrossMargin\x12(\n" +
	"\x0fOperatingMargin\x18\x0f \x01(\x01R\x0fOperatingMargin\x12\x1c\n" +
	"\tNetMargin\x18\x10 \x01(\x01R\tNetMargin\x12\x10\n" +
	"\x03EPS\x18\x11 \x01(\x01R\x03EPS\x12\x10\n" +
	"\x03BPS\x18\x12 \x01(\x01R\x03BPS\x12\x18\n" +
	"\aRevenue\x18\x13 \x01(\x01R\aRevenue\x12\x1c\n" +
	"\tNetIncome\x18\x14 \x01(\x01R\tNetIncome\x12\x16\n" +
	"\x06EBITDA\x18\x15 \x01(\x01R\x06EBITDA\x12\x12\n" +
	"\x04EBIT\x18\x16 \x01(\x01R\x04EBIT\x12,\n" +
	"\x11OperatingCashFlow\x18\x17 \x01(\x01R\x11OperatingCashFlow\x12\"\n" +
	"\fFreeCashFlow\x18\x18 \x01(\x01R\fFreeCashFlow\x12\x14\n" +
	"\x05CAPEX\x18\x19 \x01(\x01R\x05CAPEX\x12 \n" +
	"\vTotalAssets\x18\x1a \x01(\x01R\vTotalAssets\x12*\n" +
	"\x10TotalLiabilities\x18\x1b \x01(\x01R\x10TotalLiabilities\x12,\n" +
	"\x11ShareholderEquity\x18\x1c \x01(\x01R\x11ShareholderEquity\x12\"\n" +
	"\fDebtToEquity\x18\x1d \x01(\x01R\fDebtToEquity\x120\n" +
	"\x13AssetLiabilityRatio\x18\x1e \x01(\x01R\x13AssetLiabilityRatio\x12\"\n" +
	"\fCurrentRatio\x18\x1f \x01(\x01R\fCurrentRatio\x12\x1e\n" +
	"\n" +
	"QuickRatio\x18  \x01(\x01R\n" +
	"QuickRatio\x12*\n" +
	"\x10InterestCoverage\x18! \x01(\x01R\x10InterestCoverage\x12.\n" +
	"\x12CashAndEquivalents\x18\" \x01(\x01R\x12CashAndEquivalents\x12,\n" +
	"\x11SharesOutstanding\x18# \x01(\x03R\x11SharesOutstanding\x12\x1c\n" +
	"\tUpdatedAt\x18$ \x01(\x03R\tUpdatedAtB\x06Z\x04.;pbb\x06proto3"

var (
	file_company_company_db_proto_rawDescOnce sync.Once
	file_company_company_db_proto_rawDescData []byte
)

func file_company_company_db_proto_rawDescGZIP() []byte {
	file_company_company_db_proto_rawDescOnce.Do(func() {
		file_company_company_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_company_db_proto_rawDesc), len(file_company_company_db_proto_rawDesc)))
	})
	return file_company_company_db_proto_rawDescData
}

var file_company_company_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_company_company_db_proto_goTypes = []any{
	(*Company)(nil),        // 0: Company
	(*CompanyFinance)(nil), // 1: CompanyFinance
}
var file_company_company_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_company_company_db_proto_init() }
func file_company_company_db_proto_init() {
	if File_company_company_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_company_db_proto_rawDesc), len(file_company_company_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_company_company_db_proto_goTypes,
		DependencyIndexes: file_company_company_db_proto_depIdxs,
		MessageInfos:      file_company_company_db_proto_msgTypes,
	}.Build()
	File_company_company_db_proto = out.File
	file_company_company_db_proto_goTypes = nil
	file_company_company_db_proto_depIdxs = nil
}
