// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	// 必填，长度 3-100
	// example: asdasd12313asdas
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" gorm:"uid:50;primaryKey"` //@go_tags(`gorm:"uid:50;primaryKey" json:"uid"`) 用户ID
	// 邮箱
	// 必填，长度 3-100
	// example:
	Mail string `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail" gorm:"mail:50"` //@go_tags(`gorm:"mail:50" json:"mail"`) 邮箱
	// 手机号
	// 必填，长度 3-100
	// example:
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone" gorm:"phone:50"` //@go_tags(`gorm:"phone:50" json:"phone"`) 手机号
	// 用户名
	// 用户昵称
	// example:
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name" gorm:"name:50"` //@go_tags(`gorm:"name:50" json:"name"`) 用户名
	// 玩家头像
	// 用户头衔地址 https//xxxxx
	// example:
	Avatar string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar" gorm:"avatar"` //@go_tags(`gorm:"avatar" json:"avatar"`) 玩家头像
	// 耳机id
	// 耳机的设备id，完成设备绑定后 存在
	// example:
	Deviceid string `protobuf:"bytes,9,opt,name=deviceid,proto3" json:"deviceid" gorm:"deviceid"` //@go_tags(`gorm:"deviceid" json:"deviceid"`) 耳机id
	// 手机型号
	// 选填
	// example: iPhone10
	Phonemodel string `protobuf:"bytes,10,opt,name=phonemodel,proto3" json:"phonemodel"` //@go_tags(`json:"phonemodel"`) 手机型号
	// 手机硬件id
	// 选填
	// example:
	Phonemac string `protobuf:"bytes,11,opt,name=phonemac,proto3" json:"phonemac"` //@go_tags(`json:"phonemac"`) 手机硬件id
	// 登录帐号
	// 选填
	// example:
	Account string `protobuf:"bytes,12,opt,name=account,proto3" json:"account"` //@go_tags(`json:"account"`) 登录帐号
	// 账号登陆密码
	// 选填
	// example:
	Password string `protobuf:"bytes,13,opt,name=password,proto3" json:"password"` //@go_tags(`json:"password"`) 密码登录
	// 最后一次下注时间
	// 秒级时间戳
	// example:1736780920
	Lastbettime int64 `protobuf:"varint,20,opt,name=lastbettime,proto3" json:"lastbettime" gorm:"lastbettime"` //@go_tags(`gorm:"lastbettime" json:"lastbettime"`) 最后一次下注时间
	// 注册时间
	// 秒级时间戳
	// example: 1736780920
	Createtime int64 `protobuf:"varint,21,opt,name=createtime,proto3" json:"createtime" gorm:"createtime"` //@go_tags(`gorm:"createtime" json:"createtime"`) 注册时间
	// 语言
	// 玩家设置的语言
	// example:
	Language string `protobuf:"bytes,22,opt,name=language,proto3" json:"language" gorm:"language"` //@go_tags(`gorm:"language" json:"language"`) 语言
	// 授权码
	// 绑定设备需要的凭据
	// example:
	Authorizecode string `protobuf:"bytes,23,opt,name=authorizecode,proto3" json:"authorizecode" gorm:"authorizecode"` //@go_tags(`gorm:"authorizecode" json:"authorizecode"`) 授权码
	// 微信openid
	// 必填，长度 3-100
	// example:
	Wxopenid string `protobuf:"bytes,30,opt,name=wxopenid,proto3" json:"wxopenid" gorm:"wxopenid:50"` //@go_tags(`gorm:"wxopenid:50" json:"wxopenid"`) 微信openid
	// 谷歌openid
	// 必填，长度 3-100
	// example:
	Googleopenid string `protobuf:"bytes,31,opt,name=googleopenid,proto3" json:"googleopenid" gorm:"googleopenid:50"` //@go_tags(`gorm:"googleopenid:50" json:"googleopenid"`) 谷歌openid
	// 谷歌openid
	// 必填，长度 3-100
	// example:
	Facebookopenid string `protobuf:"bytes,32,opt,name=facebookopenid,proto3" json:"facebookopenid" gorm:"facebookopenid:50"` //@go_tags(`gorm:"facebookopenid:50" json:"facebookopenid"`) FaceBook
	// 谷歌openid
	// 必填，长度 3-100
	// example:
	Firebaseopenid string `protobuf:"bytes,33,opt,name=firebaseopenid,proto3" json:"firebaseopenid" gorm:"firebaseopenid:50"` //@go_tags(`gorm:"firebaseopenid:50" json:"firebaseopenid"`) Firebas
	// viplv
	// 必填，长度 3-100
	// example:
	Viplv         int32 `protobuf:"varint,40,opt,name=viplv,proto3" json:"viplv" gorm:"viplv:50"` //@go_tags(`gorm:"viplv:50" json:"viplv"`) viplv
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBUser) Reset() {
	*x = DBUser{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUser) ProtoMessage() {}

func (x *DBUser) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUser.ProtoReflect.Descriptor instead.
func (*DBUser) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUser) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *DBUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DBUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DBUser) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *DBUser) GetPhonemodel() string {
	if x != nil {
		return x.Phonemodel
	}
	return ""
}

func (x *DBUser) GetPhonemac() string {
	if x != nil {
		return x.Phonemac
	}
	return ""
}

func (x *DBUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DBUser) GetLastbettime() int64 {
	if x != nil {
		return x.Lastbettime
	}
	return 0
}

func (x *DBUser) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

func (x *DBUser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DBUser) GetAuthorizecode() string {
	if x != nil {
		return x.Authorizecode
	}
	return ""
}

func (x *DBUser) GetWxopenid() string {
	if x != nil {
		return x.Wxopenid
	}
	return ""
}

func (x *DBUser) GetGoogleopenid() string {
	if x != nil {
		return x.Googleopenid
	}
	return ""
}

func (x *DBUser) GetFacebookopenid() string {
	if x != nil {
		return x.Facebookopenid
	}
	return ""
}

func (x *DBUser) GetFirebaseopenid() string {
	if x != nil {
		return x.Firebaseopenid
	}
	return ""
}

func (x *DBUser) GetViplv() int32 {
	if x != nil {
		return x.Viplv
	}
	return 0
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\"\xa8\x04\n" +
	"\x06DBUser\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04mail\x18\x02 \x01(\tR\x04mail\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x1a\n" +
	"\bdeviceid\x18\t \x01(\tR\bdeviceid\x12\x1e\n" +
	"\n" +
	"phonemodel\x18\n" +
	" \x01(\tR\n" +
	"phonemodel\x12\x1a\n" +
	"\bphonemac\x18\v \x01(\tR\bphonemac\x12\x18\n" +
	"\aaccount\x18\f \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12 \n" +
	"\vlastbettime\x18\x14 \x01(\x03R\vlastbettime\x12\x1e\n" +
	"\n" +
	"createtime\x18\x15 \x01(\x03R\n" +
	"createtime\x12\x1a\n" +
	"\blanguage\x18\x16 \x01(\tR\blanguage\x12$\n" +
	"\rauthorizecode\x18\x17 \x01(\tR\rauthorizecode\x12\x1a\n" +
	"\bwxopenid\x18\x1e \x01(\tR\bwxopenid\x12\"\n" +
	"\fgoogleopenid\x18\x1f \x01(\tR\fgoogleopenid\x12&\n" +
	"\x0efacebookopenid\x18  \x01(\tR\x0efacebookopenid\x12&\n" +
	"\x0efirebaseopenid\x18! \x01(\tR\x0efirebaseopenid\x12\x14\n" +
	"\x05viplv\x18( \x01(\x05R\x05viplvB\x06Z\x04.;pbb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_proto_goTypes = []any{
	(*DBUser)(nil), // 0: DBUser
}
var file_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
