// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"id;primaryKey json:"` //@go_tags(`gorm:"id;primaryKey json:"id"`) id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBUser) Reset() {
	*x = DBUser{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUser) ProtoMessage() {}

func (x *DBUser) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUser.ProtoReflect.Descriptor instead.
func (*DBUser) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户股票持仓
type DBUserStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"id;primaryKey;autoIncrement json:"`                         //@go_tags(`gorm:"id;primaryKey;autoIncrement json:"id"`) id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" gorm:"user_id json:"`    //@go_tags(`gorm:"user_id json:"user_id"`) user_id
	StockId       string                 `protobuf:"bytes,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty" gorm:"stock_id json:"` //@go_tags(`gorm:"stock_id json:"stock_id"`) stock_id
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty" gorm:"amount json:"`                 //@go_tags(`gorm:"amount json:"amount"`) amount
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty" gorm:"price json:"`                   //@go_tags(`gorm:"price json:"price"`) price
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBUserStock) Reset() {
	*x = DBUserStock{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUserStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUserStock) ProtoMessage() {}

func (x *DBUserStock) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUserStock.ProtoReflect.Descriptor instead.
func (*DBUserStock) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBUserStock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBUserStock) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DBUserStock) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *DBUserStock) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBUserStock) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\"H\n" +
	"\x06DBUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x7f\n" +
	"\vDBUserStock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bstock_id\x18\x03 \x01(\tR\astockId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05priceB\x06Z\x04.;pbb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_db_proto_goTypes = []any{
	(*DBUser)(nil),      // 0: DBUser
	(*DBUserStock)(nil), // 1: DBUserStock
}
var file_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
