// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SginTyoe int32

const (
	// 邮箱登录
	// @Description 邮箱登录
	// @example
	SginTyoe_Mail SginTyoe = 0 //手机登录
	// 手机登录
	// @Description 手机登录
	// @example
	SginTyoe_Phone SginTyoe = 1 //手机登录
	// 微信登录
	// @Description 微信登录
	// @example
	SginTyoe_WXChat SginTyoe = 2 //微信登录
	// google登录
	// @Description google登录
	// @example
	SginTyoe_Google SginTyoe = 3 //google登录
	// facebook登录
	// @Description facebook登录
	// @example
	SginTyoe_FaceBook SginTyoe = 4 //facebook登录
	// Firebase登录
	// @Description Firebase登录
	// @example
	SginTyoe_Firebase SginTyoe = 5 //Firebase
)

// Enum value maps for SginTyoe.
var (
	SginTyoe_name = map[int32]string{
		0: "Mail",
		1: "Phone",
		2: "WXChat",
		3: "Google",
		4: "FaceBook",
		5: "Firebase",
	}
	SginTyoe_value = map[string]int32{
		"Mail":     0,
		"Phone":    1,
		"WXChat":   2,
		"Google":   3,
		"FaceBook": 4,
		"Firebase": 5,
	}
)

func (x SginTyoe) Enum() *SginTyoe {
	p := new(SginTyoe)
	*p = x
	return p
}

func (x SginTyoe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SginTyoe) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (SginTyoe) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x SginTyoe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SginTyoe.Descriptor instead.
func (SginTyoe) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto*S\n" +
	"\bSginTyoe\x12\b\n" +
	"\x04Mail\x10\x00\x12\t\n" +
	"\x05Phone\x10\x01\x12\n" +
	"\n" +
	"\x06WXChat\x10\x02\x12\n" +
	"\n" +
	"\x06Google\x10\x03\x12\f\n" +
	"\bFaceBook\x10\x04\x12\f\n" +
	"\bFirebase\x10\x05B\x06Z\x04.;pbb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_proto_goTypes = []any{
	(SginTyoe)(0), // 0: SginTyoe
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
