// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: errorcode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_Success                 ErrorCode = 0   //成功
	ErrorCode_GatewayException        ErrorCode = 1   //网关执行异常
	ErrorCode_NoFindService           ErrorCode = 10  //没有找到远程服务器
	ErrorCode_NoFindServiceHandleFunc ErrorCode = 11  //远程服务器未找到执行方法
	ErrorCode_RpcFuncExecutionError   ErrorCode = 12  //Rpc方法执行错误
	ErrorCode_CacheReadError          ErrorCode = 13  //缓存读取失败
	ErrorCode_SqlExecutionError       ErrorCode = 14  //数据库执行错误
	ErrorCode_ReqParameterError       ErrorCode = 15  //请求参数错误
	ErrorCode_SignError               ErrorCode = 16  //签名串错误
	ErrorCode_InsufficientPermissions ErrorCode = 17  //权限不足
	ErrorCode_NoLogin                 ErrorCode = 18  //未登录
	ErrorCode_UserSessionNobeing      ErrorCode = 19  //用户不存在
	ErrorCode_StateInvalid            ErrorCode = 20  //无效状态
	ErrorCode_DBError                 ErrorCode = 21  //数据库操作失败
	ErrorCode_SystemError             ErrorCode = 22  //通用错误
	ErrorCode_DecodeError             ErrorCode = 23  //加密串解码错误
	ErrorCode_TimestampTimeout        ErrorCode = 24  //加密串时间戳超时
	ErrorCode_PbError                 ErrorCode = 25  //pb错误
	ErrorCode_AgentUidEmpty           ErrorCode = 26  //AgentUid空
	ErrorCode_ConfigNoFound           ErrorCode = 27  //配置未找到
	ErrorCode_DecryptError            ErrorCode = 28  //解密错误
	ErrorCode_ClientError             ErrorCode = 29  //客户端错误
	ErrorCode_Exception               ErrorCode = 100 //程序执行异常
	ErrorCode_AgentBetExchangeError   ErrorCode = 101 //代理兑付错误
	ErrorCode_GameInMaintenance       ErrorCode = 102 //目标游戏维护中
	ErrorCode_NoCanBet                ErrorCode = 103 //不能下注
	ErrorCode_NoFindRoom              ErrorCode = 104 //未找到房间
	ErrorCode_AgentNofund             ErrorCode = 105 //渠道未注册
	ErrorCode_NetWorkError            ErrorCode = 106 //网络请求错误
	// api 相关错误码
	ErrorCode_VerificationExpired          ErrorCode = 1001 //验证码已失效
	ErrorCode_DeviceRegistered             ErrorCode = 2001 //设备已被注册
	ErrorCode_AuthorizeNoCanUse            ErrorCode = 2002 //授权码不可用
	ErrorCode_ExceptionAccountVerification ErrorCode = 2003 //验证账号异常
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "Success",
		1:    "GatewayException",
		10:   "NoFindService",
		11:   "NoFindServiceHandleFunc",
		12:   "RpcFuncExecutionError",
		13:   "CacheReadError",
		14:   "SqlExecutionError",
		15:   "ReqParameterError",
		16:   "SignError",
		17:   "InsufficientPermissions",
		18:   "NoLogin",
		19:   "UserSessionNobeing",
		20:   "StateInvalid",
		21:   "DBError",
		22:   "SystemError",
		23:   "DecodeError",
		24:   "TimestampTimeout",
		25:   "PbError",
		26:   "AgentUidEmpty",
		27:   "ConfigNoFound",
		28:   "DecryptError",
		29:   "ClientError",
		100:  "Exception",
		101:  "AgentBetExchangeError",
		102:  "GameInMaintenance",
		103:  "NoCanBet",
		104:  "NoFindRoom",
		105:  "AgentNofund",
		106:  "NetWorkError",
		1001: "VerificationExpired",
		2001: "DeviceRegistered",
		2002: "AuthorizeNoCanUse",
		2003: "ExceptionAccountVerification",
	}
	ErrorCode_value = map[string]int32{
		"Success":                      0,
		"GatewayException":             1,
		"NoFindService":                10,
		"NoFindServiceHandleFunc":      11,
		"RpcFuncExecutionError":        12,
		"CacheReadError":               13,
		"SqlExecutionError":            14,
		"ReqParameterError":            15,
		"SignError":                    16,
		"InsufficientPermissions":      17,
		"NoLogin":                      18,
		"UserSessionNobeing":           19,
		"StateInvalid":                 20,
		"DBError":                      21,
		"SystemError":                  22,
		"DecodeError":                  23,
		"TimestampTimeout":             24,
		"PbError":                      25,
		"AgentUidEmpty":                26,
		"ConfigNoFound":                27,
		"DecryptError":                 28,
		"ClientError":                  29,
		"Exception":                    100,
		"AgentBetExchangeError":        101,
		"GameInMaintenance":            102,
		"NoCanBet":                     103,
		"NoFindRoom":                   104,
		"AgentNofund":                  105,
		"NetWorkError":                 106,
		"VerificationExpired":          1001,
		"DeviceRegistered":             2001,
		"AuthorizeNoCanUse":            2002,
		"ExceptionAccountVerification": 2003,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errorcode_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errorcode_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errorcode_proto_rawDescGZIP(), []int{0}
}

var File_errorcode_proto protoreflect.FileDescriptor

const file_errorcode_proto_rawDesc = "" +
	"\n" +
	"\x0ferrorcode.proto*\xa7\x05\n" +
	"\tErrorCode\x12\v\n" +
	"\aSuccess\x10\x00\x12\x14\n" +
	"\x10GatewayException\x10\x01\x12\x11\n" +
	"\rNoFindService\x10\n" +
	"\x12\x1b\n" +
	"\x17NoFindServiceHandleFunc\x10\v\x12\x19\n" +
	"\x15RpcFuncExecutionError\x10\f\x12\x12\n" +
	"\x0eCacheReadError\x10\r\x12\x15\n" +
	"\x11SqlExecutionError\x10\x0e\x12\x15\n" +
	"\x11ReqParameterError\x10\x0f\x12\r\n" +
	"\tSignError\x10\x10\x12\x1b\n" +
	"\x17InsufficientPermissions\x10\x11\x12\v\n" +
	"\aNoLogin\x10\x12\x12\x16\n" +
	"\x12UserSessionNobeing\x10\x13\x12\x10\n" +
	"\fStateInvalid\x10\x14\x12\v\n" +
	"\aDBError\x10\x15\x12\x0f\n" +
	"\vSystemError\x10\x16\x12\x0f\n" +
	"\vDecodeError\x10\x17\x12\x14\n" +
	"\x10TimestampTimeout\x10\x18\x12\v\n" +
	"\aPbError\x10\x19\x12\x11\n" +
	"\rAgentUidEmpty\x10\x1a\x12\x11\n" +
	"\rConfigNoFound\x10\x1b\x12\x10\n" +
	"\fDecryptError\x10\x1c\x12\x0f\n" +
	"\vClientError\x10\x1d\x12\r\n" +
	"\tException\x10d\x12\x19\n" +
	"\x15AgentBetExchangeError\x10e\x12\x15\n" +
	"\x11GameInMaintenance\x10f\x12\f\n" +
	"\bNoCanBet\x10g\x12\x0e\n" +
	"\n" +
	"NoFindRoom\x10h\x12\x0f\n" +
	"\vAgentNofund\x10i\x12\x10\n" +
	"\fNetWorkError\x10j\x12\x18\n" +
	"\x13VerificationExpired\x10\xe9\a\x12\x15\n" +
	"\x10DeviceRegistered\x10\xd1\x0f\x12\x16\n" +
	"\x11AuthorizeNoCanUse\x10\xd2\x0f\x12!\n" +
	"\x1cExceptionAccountVerification\x10\xd3\x0fB\x06Z\x04.;pbb\x06proto3"

var (
	file_errorcode_proto_rawDescOnce sync.Once
	file_errorcode_proto_rawDescData []byte
)

func file_errorcode_proto_rawDescGZIP() []byte {
	file_errorcode_proto_rawDescOnce.Do(func() {
		file_errorcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorcode_proto_rawDesc), len(file_errorcode_proto_rawDesc)))
	})
	return file_errorcode_proto_rawDescData
}

var file_errorcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errorcode_proto_goTypes = []any{
	(ErrorCode)(0), // 0: ErrorCode
}
var file_errorcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errorcode_proto_init() }
func file_errorcode_proto_init() {
	if File_errorcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorcode_proto_rawDesc), len(file_errorcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorcode_proto_goTypes,
		DependencyIndexes: file_errorcode_proto_depIdxs,
		EnumInfos:         file_errorcode_proto_enumTypes,
	}.Build()
	File_errorcode_proto = out.File
	file_errorcode_proto_goTypes = nil
	file_errorcode_proto_depIdxs = nil
}
