// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: gateway/gateway_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//网关心跳 请求
type GatewayHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GatewayHeartbeatReq) Reset() {
	*x = GatewayHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeatReq) ProtoMessage() {}

func (x *GatewayHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeatReq.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{0}
}

//网关心跳 请求回应
type GatewayHeartbeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GatewayHeartbeatResp) Reset() {
	*x = GatewayHeartbeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayHeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeatResp) ProtoMessage() {}

func (x *GatewayHeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeatResp.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeatResp) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayHeartbeatResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

//统一错误码推送
type GatewayErrorNotifyPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName     string     `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`         //消息id 客户端标记
	ServicePath string     `protobuf:"bytes,2,opt,name=ServicePath,proto3" json:"ServicePath,omitempty"` //消息路由
	Req         *anypb.Any `protobuf:"bytes,3,opt,name=Req,proto3" json:"Req,omitempty"`                 //参数信息
	Error       *ErrorData `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`             //错误数据
}

func (x *GatewayErrorNotifyPush) Reset() {
	*x = GatewayErrorNotifyPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayErrorNotifyPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayErrorNotifyPush) ProtoMessage() {}

func (x *GatewayErrorNotifyPush) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayErrorNotifyPush.ProtoReflect.Descriptor instead.
func (*GatewayErrorNotifyPush) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayErrorNotifyPush) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *GatewayErrorNotifyPush) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *GatewayErrorNotifyPush) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GatewayErrorNotifyPush) GetError() *ErrorData {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_gateway_gateway_msg_proto protoreflect.FileDescriptor

var file_gateway_gateway_msg_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x22, 0x34, 0x0a, 0x14, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x9e, 0x01, 0x0a, 0x16, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_gateway_msg_proto_rawDescOnce sync.Once
	file_gateway_gateway_msg_proto_rawDescData = file_gateway_gateway_msg_proto_rawDesc
)

func file_gateway_gateway_msg_proto_rawDescGZIP() []byte {
	file_gateway_gateway_msg_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_gateway_msg_proto_rawDescData)
	})
	return file_gateway_gateway_msg_proto_rawDescData
}

var file_gateway_gateway_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_gateway_msg_proto_goTypes = []interface{}{
	(*GatewayHeartbeatReq)(nil),    // 0: GatewayHeartbeatReq
	(*GatewayHeartbeatResp)(nil),   // 1: GatewayHeartbeatResp
	(*GatewayErrorNotifyPush)(nil), // 2: GatewayErrorNotifyPush
	(*anypb.Any)(nil),              // 3: google.protobuf.Any
	(*ErrorData)(nil),              // 4: ErrorData
}
var file_gateway_gateway_msg_proto_depIdxs = []int32{
	3, // 0: GatewayErrorNotifyPush.Req:type_name -> google.protobuf.Any
	4, // 1: GatewayErrorNotifyPush.Error:type_name -> ErrorData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_gateway_msg_proto_init() }
func file_gateway_gateway_msg_proto_init() {
	if File_gateway_gateway_msg_proto != nil {
		return
	}
	file_comm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gateway_gateway_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gateway_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayHeartbeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gateway_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayErrorNotifyPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_gateway_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_msg_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_msg_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_msg_proto_msgTypes,
	}.Build()
	File_gateway_gateway_msg_proto = out.File
	file_gateway_gateway_msg_proto_rawDesc = nil
	file_gateway_gateway_msg_proto_goTypes = nil
	file_gateway_gateway_msg_proto_depIdxs = nil
}
