// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gateway/gateway_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 网关心跳 请求
type GatewayHeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayHeartbeatReq) Reset() {
	*x = GatewayHeartbeatReq{}
	mi := &file_gateway_gateway_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeatReq) ProtoMessage() {}

func (x *GatewayHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeatReq.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{0}
}

// 网关心跳 请求回应
type GatewayHeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayHeartbeatResp) Reset() {
	*x = GatewayHeartbeatResp{}
	mi := &file_gateway_gateway_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeatResp) ProtoMessage() {}

func (x *GatewayHeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeatResp.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeatResp) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayHeartbeatResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 统一错误码推送
type GatewayErrorNotifyPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgName       string                 `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`         //消息id 客户端标记
	ServicePath   string                 `protobuf:"bytes,2,opt,name=ServicePath,proto3" json:"ServicePath,omitempty"` //消息路由
	Req           *anypb.Any             `protobuf:"bytes,3,opt,name=Req,proto3" json:"Req,omitempty"`                 //参数信息
	Error         *ErrorData             `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`             //错误数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayErrorNotifyPush) Reset() {
	*x = GatewayErrorNotifyPush{}
	mi := &file_gateway_gateway_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayErrorNotifyPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayErrorNotifyPush) ProtoMessage() {}

func (x *GatewayErrorNotifyPush) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayErrorNotifyPush.ProtoReflect.Descriptor instead.
func (*GatewayErrorNotifyPush) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_msg_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayErrorNotifyPush) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *GatewayErrorNotifyPush) GetServicePath() string {
	if x != nil {
		return x.ServicePath
	}
	return ""
}

func (x *GatewayErrorNotifyPush) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GatewayErrorNotifyPush) GetError() *ErrorData {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_gateway_gateway_msg_proto protoreflect.FileDescriptor

const file_gateway_gateway_msg_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/gateway_msg.proto\x1a\n" +
	"comm.proto\x1a\x19google/protobuf/any.proto\"\x15\n" +
	"\x13GatewayHeartbeatReq\"4\n" +
	"\x14GatewayHeartbeatResp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x9e\x01\n" +
	"\x16GatewayErrorNotifyPush\x12\x18\n" +
	"\aMsgName\x18\x01 \x01(\tR\aMsgName\x12 \n" +
	"\vServicePath\x18\x02 \x01(\tR\vServicePath\x12&\n" +
	"\x03Req\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03Req\x12 \n" +
	"\x05Error\x18\x04 \x01(\v2\n" +
	".ErrorDataR\x05ErrorB\x06Z\x04.;pbb\x06proto3"

var (
	file_gateway_gateway_msg_proto_rawDescOnce sync.Once
	file_gateway_gateway_msg_proto_rawDescData []byte
)

func file_gateway_gateway_msg_proto_rawDescGZIP() []byte {
	file_gateway_gateway_msg_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_msg_proto_rawDesc), len(file_gateway_gateway_msg_proto_rawDesc)))
	})
	return file_gateway_gateway_msg_proto_rawDescData
}

var file_gateway_gateway_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_gateway_msg_proto_goTypes = []any{
	(*GatewayHeartbeatReq)(nil),    // 0: GatewayHeartbeatReq
	(*GatewayHeartbeatResp)(nil),   // 1: GatewayHeartbeatResp
	(*GatewayErrorNotifyPush)(nil), // 2: GatewayErrorNotifyPush
	(*anypb.Any)(nil),              // 3: google.protobuf.Any
	(*ErrorData)(nil),              // 4: ErrorData
}
var file_gateway_gateway_msg_proto_depIdxs = []int32{
	3, // 0: GatewayErrorNotifyPush.Req:type_name -> google.protobuf.Any
	4, // 1: GatewayErrorNotifyPush.Error:type_name -> ErrorData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_gateway_msg_proto_init() }
func file_gateway_gateway_msg_proto_init() {
	if File_gateway_gateway_msg_proto != nil {
		return
	}
	file_comm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_msg_proto_rawDesc), len(file_gateway_gateway_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_msg_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_msg_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_msg_proto_msgTypes,
	}.Build()
	File_gateway_gateway_msg_proto = out.File
	file_gateway_gateway_msg_proto_goTypes = nil
	file_gateway_gateway_msg_proto_depIdxs = nil
}
