// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: market_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取实时行情请求
type MarketRealtimeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketRealtimeInfoReq) Reset() {
	*x = MarketRealtimeInfoReq{}
	mi := &file_market_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketRealtimeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRealtimeInfoReq) ProtoMessage() {}

func (x *MarketRealtimeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_market_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRealtimeInfoReq.ProtoReflect.Descriptor instead.
func (*MarketRealtimeInfoReq) Descriptor() ([]byte, []int) {
	return file_market_msg_proto_rawDescGZIP(), []int{0}
}

// 获取实时行情响应
type MarketRealtimeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketRealtimeInfoResp) Reset() {
	*x = MarketRealtimeInfoResp{}
	mi := &file_market_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketRealtimeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRealtimeInfoResp) ProtoMessage() {}

func (x *MarketRealtimeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_market_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRealtimeInfoResp.ProtoReflect.Descriptor instead.
func (*MarketRealtimeInfoResp) Descriptor() ([]byte, []int) {
	return file_market_msg_proto_rawDescGZIP(), []int{1}
}

var File_market_msg_proto protoreflect.FileDescriptor

const file_market_msg_proto_rawDesc = "" +
	"\n" +
	"\x10market_msg.proto\"\x17\n" +
	"\x15MarketRealtimeInfoReq\"\x18\n" +
	"\x16MarketRealtimeInfoRespB\x06Z\x04.;pbb\x06proto3"

var (
	file_market_msg_proto_rawDescOnce sync.Once
	file_market_msg_proto_rawDescData []byte
)

func file_market_msg_proto_rawDescGZIP() []byte {
	file_market_msg_proto_rawDescOnce.Do(func() {
		file_market_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_msg_proto_rawDesc), len(file_market_msg_proto_rawDesc)))
	})
	return file_market_msg_proto_rawDescData
}

var file_market_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_msg_proto_goTypes = []any{
	(*MarketRealtimeInfoReq)(nil),  // 0: MarketRealtimeInfoReq
	(*MarketRealtimeInfoResp)(nil), // 1: MarketRealtimeInfoResp
}
var file_market_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_msg_proto_init() }
func file_market_msg_proto_init() {
	if File_market_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_msg_proto_rawDesc), len(file_market_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_msg_proto_goTypes,
		DependencyIndexes: file_market_msg_proto_depIdxs,
		MessageInfos:      file_market_msg_proto_msgTypes,
	}.Build()
	File_market_msg_proto = out.File
	file_market_msg_proto_goTypes = nil
	file_market_msg_proto_depIdxs = nil
}
