// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: market/market_db.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 市场实时指数数据
type DBMarketIndexRealTimeItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Index                int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index" gorm:"primaryKey"`                                                                                  //@go_tags(`gorm:"primaryKey" json:"index"`) 序号
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code" gorm:"column:Code"`                                                                                    //@go_tags(`gorm:"column:Code" json:"code"`) 指数代码，如“000001”
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" gorm:"column:Name"`                                                                                    //@go_tags(`gorm:"column:Name" json:"name"`) 指数名称，如“上证指数”
	LastPrice            float64                `protobuf:"fixed64,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price" gorm:"column:lastprice"`                                                  //@go_tags(`gorm:"column:lastprice" json:"last_price"`) 最新价
	ChangePct            float64                `protobuf:"fixed64,5,opt,name=change_pct,json=changePct,proto3" json:"change_pct" gorm:"column:change_pct"`                                                 //@go_tags(`gorm:"column:change_pct" json:"change_pct"`) 涨跌幅
	ChangeAmt            float64                `protobuf:"fixed64,6,opt,name=change_amt,json=changeAmt,proto3" json:"change_amt" gorm:"column:change_amt"`                                                 //@go_tags(`gorm:"column:change_amt" json:"change_amt"`) 涨跌额
	Volume               float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume" gorm:"column:volume"`                                                                            //@go_tags(`gorm:"column:volume" json:"volume"`) 成交量
	Amount               float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount" gorm:"column:amount"`                                                                            //@go_tags(`gorm:"column:amount" json:"amount"`) 成交额
	Amplitude            float64                `protobuf:"fixed64,9,opt,name=amplitude,proto3" json:"amplitude" gorm:"column:amplitude"`                                                                   //@go_tags(`gorm:"column:amplitude" json:"amplitude"`) 振幅
	High                 float64                `protobuf:"fixed64,10,opt,name=high,proto3" json:"high" gorm:"column:high"`                                                                                 //@go_tags(`gorm:"column:high" json:"high"`) 最高
	Low                  float64                `protobuf:"fixed64,11,opt,name=low,proto3" json:"low" gorm:"column:low"`                                                                                    //@go_tags(`gorm:"column:low" json:"low"`) 最低
	Open                 float64                `protobuf:"fixed64,12,opt,name=open,proto3" json:"open" gorm:"column:open"`                                                                                 //@go_tags(`gorm:"column:open" json:"open"`) 今开
	PrevClose            float64                `protobuf:"fixed64,13,opt,name=prev_close,json=prevClose,proto3" json:"prev_close" gorm:"column:prev_close"`                                                //@go_tags(`gorm:"column:prev_close" json:"prev_close"`) 昨收
	VolumeRatio          float64                `protobuf:"fixed64,14,opt,name=volume_ratio,json=volumeRatio,proto3" json:"volume_ratio" gorm:"column:volume_ratio"`                                        //@go_tags(`gorm:"column:volume_ratio" json:"volume_ratio"`) 量比
	TurnoverRate         float64                `protobuf:"fixed64,15,opt,name=turnover_rate,json=turnoverRate,proto3" json:"turnover_rate" gorm:"column:turnover_rate"`                                    //@go_tags(`gorm:"column:turnover_rate" json:"turnover_rate"`) 换手率
	PeDynamic            float64                `protobuf:"fixed64,16,opt,name=pe_dynamic,json=peDynamic,proto3" json:"pe_dynamic" gorm:"column:pe_dynamic"`                                                //@go_tags(`gorm:"column:pe_dynamic" json:"pe_dynamic"`) 市盈率-动态
	PbRatio              float64                `protobuf:"fixed64,17,opt,name=pb_ratio,json=pbRatio,proto3" json:"pb_ratio" gorm:"column:pb_ratio"`                                                        //@go_tags(`gorm:"column:pb_ratio" json:"pb_ratio"`) 市净率
	TotalMarketCap       float64                `protobuf:"fixed64,18,opt,name=total_market_cap,json=totalMarketCap,proto3" json:"total_market_cap" gorm:"column:total_market_cap"`                         //@go_tags(`gorm:"column:total_market_cap" json:"total_market_cap"`) 总市值
	CirculatingMarketCap float64                `protobuf:"fixed64,19,opt,name=circulating_market_cap,json=circulatingMarketCap,proto3" json:"circulating_market_cap" gorm:"column:circulating_market_cap"` //@go_tags(`gorm:"column:circulating_market_cap" json:"circulating_market_cap"`) 流通市值
	PriceSpeed           float64                `protobuf:"fixed64,20,opt,name=price_speed,json=priceSpeed,proto3" json:"price_speed" gorm:"column:price_speed"`                                            //@go_tags(`gorm:"column:price_speed" json:"price_speed"`) 涨速
	FiveMinChange        float64                `protobuf:"fixed64,21,opt,name=five_min_change,json=fiveMinChange,proto3" json:"five_min_change" gorm:"column:five_min_change"`                             //@go_tags(`gorm:"column:five_min_change" json:"five_min_change"`) 5分钟涨跌
	SixtyDayChangePct    float64                `protobuf:"fixed64,22,opt,name=sixty_day_change_pct,json=sixtyDayChangePct,proto3" json:"sixty_day_change_pct" gorm:"column:sixty_day_change_pct"`          //@go_tags(`gorm:"column:sixty_day_change_pct" json:"sixty_day_change_pct"`) 60日涨跌幅
	YtdChangePct         float64                `protobuf:"fixed64,23,opt,name=ytd_change_pct,json=ytdChangePct,proto3" json:"ytd_change_pct" gorm:"column:ytd_change_pct"`                                 //@go_tags(`gorm:"column:ytd_change_pct" json:"ytd_change_pct"`) 年初至今涨跌幅
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DBMarketIndexRealTimeItem) Reset() {
	*x = DBMarketIndexRealTimeItem{}
	mi := &file_market_market_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBMarketIndexRealTimeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMarketIndexRealTimeItem) ProtoMessage() {}

func (x *DBMarketIndexRealTimeItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMarketIndexRealTimeItem.ProtoReflect.Descriptor instead.
func (*DBMarketIndexRealTimeItem) Descriptor() ([]byte, []int) {
	return file_market_market_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBMarketIndexRealTimeItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DBMarketIndexRealTimeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBMarketIndexRealTimeItem) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetChangeAmt() float64 {
	if x != nil {
		return x.ChangeAmt
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetAmplitude() float64 {
	if x != nil {
		return x.Amplitude
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPrevClose() float64 {
	if x != nil {
		return x.PrevClose
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetVolumeRatio() float64 {
	if x != nil {
		return x.VolumeRatio
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetTurnoverRate() float64 {
	if x != nil {
		return x.TurnoverRate
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPeDynamic() float64 {
	if x != nil {
		return x.PeDynamic
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPbRatio() float64 {
	if x != nil {
		return x.PbRatio
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetTotalMarketCap() float64 {
	if x != nil {
		return x.TotalMarketCap
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetCirculatingMarketCap() float64 {
	if x != nil {
		return x.CirculatingMarketCap
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPriceSpeed() float64 {
	if x != nil {
		return x.PriceSpeed
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetFiveMinChange() float64 {
	if x != nil {
		return x.FiveMinChange
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetSixtyDayChangePct() float64 {
	if x != nil {
		return x.SixtyDayChangePct
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetYtdChangePct() float64 {
	if x != nil {
		return x.YtdChangePct
	}
	return 0
}

var File_market_market_db_proto protoreflect.FileDescriptor

const file_market_market_db_proto_rawDesc = "" +
	"\n" +
	"\x16market/market_db.proto\"\xdf\x05\n" +
	"\x19DBMarketIndexRealTimeItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"last_price\x18\x04 \x01(\x01R\tlastPrice\x12\x1d\n" +
	"\n" +
	"change_pct\x18\x05 \x01(\x01R\tchangePct\x12\x1d\n" +
	"\n" +
	"change_amt\x18\x06 \x01(\x01R\tchangeAmt\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x1c\n" +
	"\tamplitude\x18\t \x01(\x01R\tamplitude\x12\x12\n" +
	"\x04high\x18\n" +
	" \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\v \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\f \x01(\x01R\x04open\x12\x1d\n" +
	"\n" +
	"prev_close\x18\r \x01(\x01R\tprevClose\x12!\n" +
	"\fvolume_ratio\x18\x0e \x01(\x01R\vvolumeRatio\x12#\n" +
	"\rturnover_rate\x18\x0f \x01(\x01R\fturnoverRate\x12\x1d\n" +
	"\n" +
	"pe_dynamic\x18\x10 \x01(\x01R\tpeDynamic\x12\x19\n" +
	"\bpb_ratio\x18\x11 \x01(\x01R\apbRatio\x12(\n" +
	"\x10total_market_cap\x18\x12 \x01(\x01R\x0etotalMarketCap\x124\n" +
	"\x16circulating_market_cap\x18\x13 \x01(\x01R\x14circulatingMarketCap\x12\x1f\n" +
	"\vprice_speed\x18\x14 \x01(\x01R\n" +
	"priceSpeed\x12&\n" +
	"\x0ffive_min_change\x18\x15 \x01(\x01R\rfiveMinChange\x12/\n" +
	"\x14sixty_day_change_pct\x18\x16 \x01(\x01R\x11sixtyDayChangePct\x12$\n" +
	"\x0eytd_change_pct\x18\x17 \x01(\x01R\fytdChangePctB\x06Z\x04.;pbb\x06proto3"

var (
	file_market_market_db_proto_rawDescOnce sync.Once
	file_market_market_db_proto_rawDescData = file_market_market_db_proto_rawDesc
)

func file_market_market_db_proto_rawDescGZIP() []byte {
	file_market_market_db_proto_rawDescOnce.Do(func() {
		file_market_market_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_market_db_proto_rawDescData)
	})
	return file_market_market_db_proto_rawDescData
}

var file_market_market_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_market_db_proto_goTypes = []any{
	(*DBMarketIndexRealTimeItem)(nil), // 0: DBMarketIndexRealTimeItem
}
var file_market_market_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_market_db_proto_init() }
func file_market_market_db_proto_init() {
	if File_market_market_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_market_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMarketSpotItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_market_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_market_db_proto_goTypes,
		DependencyIndexes: file_market_market_db_proto_depIdxs,
		MessageInfos:      file_market_market_db_proto_msgTypes,
	}.Build()
	File_market_market_db_proto = out.File
	file_market_market_db_proto_rawDesc = nil
	file_market_market_db_proto_goTypes = nil
	file_market_market_db_proto_depIdxs = nil
}
