// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: market/market_msg.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取实时行情请求
type MarketGetRealTimeIndexsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarketGetRealTimeIndexsReq) Reset() {
	*x = MarketGetRealTimeIndexsReq{}
	mi := &file_market_market_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketGetRealTimeIndexsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketGetRealTimeIndexsReq) ProtoMessage() {}

func (x *MarketGetRealTimeIndexsReq) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketGetRealTimeIndexsReq.ProtoReflect.Descriptor instead.
func (*MarketGetRealTimeIndexsReq) Descriptor() ([]byte, []int) {
	return file_market_market_msg_proto_rawDescGZIP(), []int{0}
}

// 获取实时行情响应
type MarketGetRealTimeIndexsResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*DBMarketIndexRealTimeItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"items"` //@go_tags(`json:"items"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DBMarketSpotItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"items"`
}

func (x *MarketGetRealTimeIndexsResp) Reset() {
	*x = MarketGetRealTimeIndexsResp{}
	mi := &file_market_market_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketGetRealTimeIndexsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketGetRealTimeIndexsResp) ProtoMessage() {}

func (x *MarketGetRealTimeIndexsResp) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketGetRealTimeIndexsResp.ProtoReflect.Descriptor instead.
func (*MarketGetRealTimeIndexsResp) Descriptor() ([]byte, []int) {
	return file_market_market_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MarketGetRealTimeIndexsResp) GetItems() []*DBMarketIndexRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_market_market_msg_proto protoreflect.FileDescriptor

const file_market_market_msg_proto_rawDesc = "" +
	"\n" +
	"\x17market/market_msg.proto\x1a\x16market/market_db.proto\"\x1c\n" +
	"\x1aMarketGetRealTimeIndexsReq\"O\n" +
	"\x1bMarketGetRealTimeIndexsResp\x120\n" +
	"\x05Items\x18\x01 \x03(\v2\x1a.DBMarketIndexRealTimeItemR\x05ItemsB\x06Z\x04.;pbb\x06proto3"

var (
	file_market_market_msg_proto_rawDescOnce sync.Once
	file_market_market_msg_proto_rawDescData = file_market_market_msg_proto_rawDesc
)

func file_market_market_msg_proto_rawDescGZIP() []byte {
	file_market_market_msg_proto_rawDescOnce.Do(func() {
		file_market_market_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_market_msg_proto_rawDescData)
	})
	return file_market_market_msg_proto_rawDescData
}

var file_market_market_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_market_msg_proto_goTypes = []any{
	(*MarketGetRealTimeIndexsReq)(nil),  // 0: MarketGetRealTimeIndexsReq
	(*MarketGetRealTimeIndexsResp)(nil), // 1: MarketGetRealTimeIndexsResp
	(*DBMarketIndexRealTimeItem)(nil),   // 2: DBMarketIndexRealTimeItem
}
var file_market_market_msg_proto_depIdxs = []int32{
	2, // 0: MarketGetRealTimeIndexsResp.Items:type_name -> DBMarketIndexRealTimeItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_market_msg_proto_init() }
func file_market_market_msg_proto_init() {
	if File_market_market_msg_proto != nil {
		return
	}
	file_market_market_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_market_market_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketGetSpotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_market_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketGetSpotsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_market_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_market_msg_proto_goTypes,
		DependencyIndexes: file_market_market_msg_proto_depIdxs,
		MessageInfos:      file_market_market_msg_proto_msgTypes,
	}.Build()
	File_market_market_msg_proto = out.File
	file_market_market_msg_proto_rawDesc = nil
	file_market_market_msg_proto_goTypes = nil
	file_market_market_msg_proto_depIdxs = nil
}
