// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: market/market_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//获取实时行情请求
type MarketGetSpotsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarketGetSpotsReq) Reset() {
	*x = MarketGetSpotsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_market_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketGetSpotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketGetSpotsReq) ProtoMessage() {}

func (x *MarketGetSpotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketGetSpotsReq.ProtoReflect.Descriptor instead.
func (*MarketGetSpotsReq) Descriptor() ([]byte, []int) {
	return file_market_market_msg_proto_rawDescGZIP(), []int{0}
}

//
//获取实时行情响应
type MarketGetSpotsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DBMarketSpotItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"items"`
}

func (x *MarketGetSpotsResp) Reset() {
	*x = MarketGetSpotsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_market_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketGetSpotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketGetSpotsResp) ProtoMessage() {}

func (x *MarketGetSpotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketGetSpotsResp.ProtoReflect.Descriptor instead.
func (*MarketGetSpotsResp) Descriptor() ([]byte, []int) {
	return file_market_market_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MarketGetSpotsResp) GetItems() []*DBMarketSpotItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_market_market_msg_proto protoreflect.FileDescriptor

var file_market_market_msg_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74, 0x53, 0x70,
	0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x12, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x42,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x53, 0x70, 0x6f, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_market_msg_proto_rawDescOnce sync.Once
	file_market_market_msg_proto_rawDescData = file_market_market_msg_proto_rawDesc
)

func file_market_market_msg_proto_rawDescGZIP() []byte {
	file_market_market_msg_proto_rawDescOnce.Do(func() {
		file_market_market_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_market_msg_proto_rawDescData)
	})
	return file_market_market_msg_proto_rawDescData
}

var file_market_market_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_market_market_msg_proto_goTypes = []interface{}{
	(*MarketGetSpotsReq)(nil),  // 0: MarketGetSpotsReq
	(*MarketGetSpotsResp)(nil), // 1: MarketGetSpotsResp
	(*DBMarketSpotItem)(nil),   // 2: DBMarketSpotItem
}
var file_market_market_msg_proto_depIdxs = []int32{
	2, // 0: MarketGetSpotsResp.Items:type_name -> DBMarketSpotItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_market_msg_proto_init() }
func file_market_market_msg_proto_init() {
	if File_market_market_msg_proto != nil {
		return
	}
	file_market_market_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_market_market_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketGetSpotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_market_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketGetSpotsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_market_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_market_msg_proto_goTypes,
		DependencyIndexes: file_market_market_msg_proto_depIdxs,
		MessageInfos:      file_market_market_msg_proto_msgTypes,
	}.Build()
	File_market_market_msg_proto = out.File
	file_market_market_msg_proto_rawDesc = nil
	file_market_market_msg_proto_goTypes = nil
	file_market_market_msg_proto_depIdxs = nil
}
