// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: market/market_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 指数实时快照（东方财富 stock_zh_index_spot）
type DBMarketSpotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`             // 指数代码，如“000001”
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`             // 指数名称，如“上证指数”
	Last          float64                `protobuf:"fixed64,3,opt,name=Last,proto3" json:"Last,omitempty"`           // 最新价
	ChangePct     float64                `protobuf:"fixed64,4,opt,name=ChangePct,proto3" json:"ChangePct,omitempty"` // 涨跌幅
	TurnOver      float64                `protobuf:"fixed64,5,opt,name=TurnOver,proto3" json:"TurnOver,omitempty"`   // 成交额（元）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBMarketSpotItem) Reset() {
	*x = DBMarketSpotItem{}
	mi := &file_market_market_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBMarketSpotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMarketSpotItem) ProtoMessage() {}

func (x *DBMarketSpotItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMarketSpotItem.ProtoReflect.Descriptor instead.
func (*DBMarketSpotItem) Descriptor() ([]byte, []int) {
	return file_market_market_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBMarketSpotItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DBMarketSpotItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBMarketSpotItem) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *DBMarketSpotItem) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *DBMarketSpotItem) GetTurnOver() float64 {
	if x != nil {
		return x.TurnOver
	}
	return 0
}

var File_market_market_db_proto protoreflect.FileDescriptor

const file_market_market_db_proto_rawDesc = "" +
	"\n" +
	"\x16market/market_db.proto\"\x88\x01\n" +
	"\x10DBMarketSpotItem\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Last\x18\x03 \x01(\x01R\x04Last\x12\x1c\n" +
	"\tChangePct\x18\x04 \x01(\x01R\tChangePct\x12\x1a\n" +
	"\bTurnOver\x18\x05 \x01(\x01R\bTurnOverB\x06Z\x04.;pbb\x06proto3"

var (
	file_market_market_db_proto_rawDescOnce sync.Once
	file_market_market_db_proto_rawDescData []byte
)

func file_market_market_db_proto_rawDescGZIP() []byte {
	file_market_market_db_proto_rawDescOnce.Do(func() {
		file_market_market_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_market_db_proto_rawDesc), len(file_market_market_db_proto_rawDesc)))
	})
	return file_market_market_db_proto_rawDescData
}

var file_market_market_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_market_db_proto_goTypes = []any{
	(*DBMarketSpotItem)(nil), // 0: DBMarketSpotItem
}
var file_market_market_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_market_db_proto_init() }
func file_market_market_db_proto_init() {
	if File_market_market_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_market_db_proto_rawDesc), len(file_market_market_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_market_db_proto_goTypes,
		DependencyIndexes: file_market_market_db_proto_depIdxs,
		MessageInfos:      file_market_market_db_proto_msgTypes,
	}.Build()
	File_market_market_db_proto = out.File
	file_market_market_db_proto_goTypes = nil
	file_market_market_db_proto_depIdxs = nil
}
