// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: market/market_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//市场实时指数数据
type DBMarketIndexRealTimeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index                int64   `protobuf:"varint,1,opt,name=index,proto3" json:"index" gorm:"primaryKey"`                                                                                  //序号
	Code                 string  `protobuf:"bytes,2,opt,name=code,proto3" json:"code" gorm:"column:Code"`                                                                                    //指数代码，如“000001”
	Name                 string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name" gorm:"column:Name"`                                                                                    //指数名称，如“上证指数”
	LastPrice            float64 `protobuf:"fixed64,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price" gorm:"column:lastprice"`                                                  //最新价
	ChangePct            float64 `protobuf:"fixed64,5,opt,name=change_pct,json=changePct,proto3" json:"change_pct" gorm:"column:change_pct"`                                                 //涨跌幅
	ChangeAmt            float64 `protobuf:"fixed64,6,opt,name=change_amt,json=changeAmt,proto3" json:"change_amt" gorm:"column:change_amt"`                                                 //涨跌额
	Volume               float64 `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume" gorm:"column:volume"`                                                                            //成交量
	Amount               float64 `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount" gorm:"column:amount"`                                                                            //成交额
	Amplitude            float64 `protobuf:"fixed64,9,opt,name=amplitude,proto3" json:"amplitude" gorm:"column:amplitude"`                                                                   //振幅
	High                 float64 `protobuf:"fixed64,10,opt,name=high,proto3" json:"high" gorm:"column:high"`                                                                                 //最高
	Low                  float64 `protobuf:"fixed64,11,opt,name=low,proto3" json:"low" gorm:"column:low"`                                                                                    //最低
	Open                 float64 `protobuf:"fixed64,12,opt,name=open,proto3" json:"open" gorm:"column:open"`                                                                                 //今开
	PrevClose            float64 `protobuf:"fixed64,13,opt,name=prev_close,json=prevClose,proto3" json:"prev_close" gorm:"column:prev_close"`                                                //昨收
	VolumeRatio          float64 `protobuf:"fixed64,14,opt,name=volume_ratio,json=volumeRatio,proto3" json:"volume_ratio" gorm:"column:volume_ratio"`                                        //量比
	TurnoverRate         float64 `protobuf:"fixed64,15,opt,name=turnover_rate,json=turnoverRate,proto3" json:"turnover_rate" gorm:"column:turnover_rate"`                                    //换手率
	PeDynamic            float64 `protobuf:"fixed64,16,opt,name=pe_dynamic,json=peDynamic,proto3" json:"pe_dynamic" gorm:"column:pe_dynamic"`                                                //市盈率-动态
	PbRatio              float64 `protobuf:"fixed64,17,opt,name=pb_ratio,json=pbRatio,proto3" json:"pb_ratio" gorm:"column:pb_ratio"`                                                        //市净率
	TotalMarketCap       float64 `protobuf:"fixed64,18,opt,name=total_market_cap,json=totalMarketCap,proto3" json:"total_market_cap" gorm:"column:total_market_cap"`                         //总市值
	CirculatingMarketCap float64 `protobuf:"fixed64,19,opt,name=circulating_market_cap,json=circulatingMarketCap,proto3" json:"circulating_market_cap" gorm:"column:circulating_market_cap"` //流通市值
	PriceSpeed           float64 `protobuf:"fixed64,20,opt,name=price_speed,json=priceSpeed,proto3" json:"price_speed" gorm:"column:price_speed"`                                            //涨速
	FiveMinChange        float64 `protobuf:"fixed64,21,opt,name=five_min_change,json=fiveMinChange,proto3" json:"five_min_change" gorm:"column:five_min_change"`                             //5分钟涨跌
	SixtyDayChangePct    float64 `protobuf:"fixed64,22,opt,name=sixty_day_change_pct,json=sixtyDayChangePct,proto3" json:"sixty_day_change_pct" gorm:"column:sixty_day_change_pct"`          //60日涨跌幅
	YtdChangePct         float64 `protobuf:"fixed64,23,opt,name=ytd_change_pct,json=ytdChangePct,proto3" json:"ytd_change_pct" gorm:"column:ytd_change_pct"`                                 //年初至今涨跌幅
}

func (x *DBMarketIndexRealTimeItem) Reset() {
	*x = DBMarketIndexRealTimeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_market_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMarketIndexRealTimeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMarketIndexRealTimeItem) ProtoMessage() {}

func (x *DBMarketIndexRealTimeItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_market_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMarketIndexRealTimeItem.ProtoReflect.Descriptor instead.
func (*DBMarketIndexRealTimeItem) Descriptor() ([]byte, []int) {
	return file_market_market_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBMarketIndexRealTimeItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DBMarketIndexRealTimeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBMarketIndexRealTimeItem) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetChangeAmt() float64 {
	if x != nil {
		return x.ChangeAmt
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetAmplitude() float64 {
	if x != nil {
		return x.Amplitude
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPrevClose() float64 {
	if x != nil {
		return x.PrevClose
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetVolumeRatio() float64 {
	if x != nil {
		return x.VolumeRatio
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetTurnoverRate() float64 {
	if x != nil {
		return x.TurnoverRate
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPeDynamic() float64 {
	if x != nil {
		return x.PeDynamic
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPbRatio() float64 {
	if x != nil {
		return x.PbRatio
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetTotalMarketCap() float64 {
	if x != nil {
		return x.TotalMarketCap
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetCirculatingMarketCap() float64 {
	if x != nil {
		return x.CirculatingMarketCap
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetPriceSpeed() float64 {
	if x != nil {
		return x.PriceSpeed
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetFiveMinChange() float64 {
	if x != nil {
		return x.FiveMinChange
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetSixtyDayChangePct() float64 {
	if x != nil {
		return x.SixtyDayChangePct
	}
	return 0
}

func (x *DBMarketIndexRealTimeItem) GetYtdChangePct() float64 {
	if x != nil {
		return x.YtdChangePct
	}
	return 0
}

var File_market_market_db_proto protoreflect.FileDescriptor

var file_market_market_db_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f,
	0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x05, 0x0a, 0x19, 0x44, 0x42, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x63,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50,
	0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x6d, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x6d,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68,
	0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65,
	0x76, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70,
	0x72, 0x65, 0x76, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x65, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x62, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x70, 0x62, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x70, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x43, 0x61, 0x70, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x70, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x63, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x61, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x66,
	0x69, 0x76, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x66, 0x69, 0x76, 0x65, 0x4d, 0x69, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x14, 0x73, 0x69, 0x78, 0x74, 0x79, 0x5f, 0x64, 0x61, 0x79,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x63, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x73, 0x69, 0x78, 0x74, 0x79, 0x44, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x79, 0x74, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x5f, 0x70, 0x63, 0x74, 0x18, 0x17, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x79, 0x74,
	0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x63, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_market_db_proto_rawDescOnce sync.Once
	file_market_market_db_proto_rawDescData = file_market_market_db_proto_rawDesc
)

func file_market_market_db_proto_rawDescGZIP() []byte {
	file_market_market_db_proto_rawDescOnce.Do(func() {
		file_market_market_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_market_db_proto_rawDescData)
	})
	return file_market_market_db_proto_rawDescData
}

var file_market_market_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_market_db_proto_goTypes = []interface{}{
	(*DBMarketIndexRealTimeItem)(nil), // 0: DBMarketIndexRealTimeItem
}
var file_market_market_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_market_db_proto_init() }
func file_market_market_db_proto_init() {
	if File_market_market_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_market_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMarketIndexRealTimeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_market_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_market_db_proto_goTypes,
		DependencyIndexes: file_market_market_db_proto_depIdxs,
		MessageInfos:      file_market_market_db_proto_msgTypes,
	}.Build()
	File_market_market_db_proto = out.File
	file_market_market_db_proto_rawDesc = nil
	file_market_market_db_proto_goTypes = nil
	file_market_market_db_proto_depIdxs = nil
}
