// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: news/news_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / 市场新闻
type DBMarketNews struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         //@go_tags(`gorm:"id:50;primaryKey" json:"id"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                                       //@go_tags(`json:"tag" comment:"标签/标题"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                               //@go_tags(`json:"summary" comment:"摘要"`
	IntervalTime  string                 `protobuf:"bytes,4,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"` //@go_tags(`json:"interval_time" comment:"时间区间/显示时间"`
	PubTime       string                 `protobuf:"bytes,5,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`                //@go_tags(`json:"pub_time" comment:"发布时间(精确)"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`                                       //@go_tags(`json:"url" comment:"链接"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBMarketNews) Reset() {
	*x = DBMarketNews{}
	mi := &file_news_news_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBMarketNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMarketNews) ProtoMessage() {}

func (x *DBMarketNews) ProtoReflect() protoreflect.Message {
	mi := &file_news_news_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMarketNews.ProtoReflect.Descriptor instead.
func (*DBMarketNews) Descriptor() ([]byte, []int) {
	return file_news_news_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBMarketNews) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBMarketNews) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DBMarketNews) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DBMarketNews) GetIntervalTime() string {
	if x != nil {
		return x.IntervalTime
	}
	return ""
}

func (x *DBMarketNews) GetPubTime() string {
	if x != nil {
		return x.PubTime
	}
	return ""
}

func (x *DBMarketNews) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_news_news_db_proto protoreflect.FileDescriptor

const file_news_news_db_proto_rawDesc = "" +
	"\n" +
	"\x12news/news_db.proto\"\x9c\x01\n" +
	"\fDBMarketNews\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12#\n" +
	"\rinterval_time\x18\x04 \x01(\tR\fintervalTime\x12\x19\n" +
	"\bpub_time\x18\x05 \x01(\tR\apubTime\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03urlB\x06Z\x04.;pbb\x06proto3"

var (
	file_news_news_db_proto_rawDescOnce sync.Once
	file_news_news_db_proto_rawDescData []byte
)

func file_news_news_db_proto_rawDescGZIP() []byte {
	file_news_news_db_proto_rawDescOnce.Do(func() {
		file_news_news_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_news_db_proto_rawDesc), len(file_news_news_db_proto_rawDesc)))
	})
	return file_news_news_db_proto_rawDescData
}

var file_news_news_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_news_news_db_proto_goTypes = []any{
	(*DBMarketNews)(nil), // 0: DBMarketNews
}
var file_news_news_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_news_news_db_proto_init() }
func file_news_news_db_proto_init() {
	if File_news_news_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_news_db_proto_rawDesc), len(file_news_news_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_news_news_db_proto_goTypes,
		DependencyIndexes: file_news_news_db_proto_depIdxs,
		MessageInfos:      file_news_news_db_proto_msgTypes,
	}.Build()
	File_news_news_db_proto = out.File
	file_news_news_db_proto_goTypes = nil
	file_news_news_db_proto_depIdxs = nil
}
