// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: news/news_db.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / 市场新闻
type DBRealTimeGlobalNews struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title" gorm:"title"`                                       //@go_tags(`gorm:"title" json:"title"`) 标题
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content" gorm:"content"`                                 //@go_tags(`gorm:"content" json:"content"`) 内容
	PublishTime   string                 `protobuf:"bytes,3,opt,name=publish_time,json=publishTime,proto3" json:"publish_time" gorm:"publish_time"` //@go_tags(`gorm:"publish_time" json:"publish_time"`) 发布时间
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url" gorm:"url"`                                             //@go_tags(`gorm:"url" json:"url"`) 链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         //@go_tags(`gorm:"id:50;primaryKey" json:"id"`
	Tag          string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                                       //@go_tags(`json:"tag" comment:"标签/标题"`
	Summary      string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                               //@go_tags(`json:"summary" comment:"摘要"`
	IntervalTime string `protobuf:"bytes,4,opt,name=interval_time,json=intervalTime,proto3" json:"interval_time,omitempty"` //@go_tags(`json:"interval_time" comment:"时间区间/显示时间"`
	PubTime      string `protobuf:"bytes,5,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`                //@go_tags(`json:"pub_time" comment:"发布时间(精确)"`
	Url          string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`                                       //@go_tags(`json:"url" comment:"链接"`
}

func (x *DBRealTimeGlobalNews) Reset() {
	*x = DBRealTimeGlobalNews{}
	mi := &file_news_news_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBRealTimeGlobalNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRealTimeGlobalNews) ProtoMessage() {}

func (x *DBRealTimeGlobalNews) ProtoReflect() protoreflect.Message {
	mi := &file_news_news_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRealTimeGlobalNews.ProtoReflect.Descriptor instead.
func (*DBRealTimeGlobalNews) Descriptor() ([]byte, []int) {
	return file_news_news_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBRealTimeGlobalNews) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DBRealTimeGlobalNews) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DBRealTimeGlobalNews) GetPublishTime() string {
	if x != nil {
		return x.PublishTime
	}
	return ""
}

func (x *DBRealTimeGlobalNews) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_news_news_db_proto protoreflect.FileDescriptor

const file_news_news_db_proto_rawDesc = "" +
	"\n" +
	"\x12news/news_db.proto\"{\n" +
	"\x14DBRealTimeGlobalNews\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fpublish_time\x18\x03 \x01(\tR\vpublishTime\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03urlB\x06Z\x04.;pbb\x06proto3"

var (
	file_news_news_db_proto_rawDescOnce sync.Once
	file_news_news_db_proto_rawDescData = file_news_news_db_proto_rawDesc
)

func file_news_news_db_proto_rawDescGZIP() []byte {
	file_news_news_db_proto_rawDescOnce.Do(func() {
		file_news_news_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_news_news_db_proto_rawDescData)
	})
	return file_news_news_db_proto_rawDescData
}

var file_news_news_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_news_news_db_proto_goTypes = []any{
	(*DBRealTimeGlobalNews)(nil), // 0: DBRealTimeGlobalNews
}
var file_news_news_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_news_news_db_proto_init() }
func file_news_news_db_proto_init() {
	if File_news_news_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_news_news_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMarketNews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_news_news_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_news_news_db_proto_goTypes,
		DependencyIndexes: file_news_news_db_proto_depIdxs,
		MessageInfos:      file_news_news_db_proto_msgTypes,
	}.Build()
	File_news_news_db_proto = out.File
	file_news_news_db_proto_rawDesc = nil
	file_news_news_db_proto_goTypes = nil
	file_news_news_db_proto_depIdxs = nil
}
