// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: news/news_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取市场新闻请求
type NewsMarketNewsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsMarketNewsReq) Reset() {
	*x = NewsMarketNewsReq{}
	mi := &file_news_news_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsMarketNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsMarketNewsReq) ProtoMessage() {}

func (x *NewsMarketNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_news_news_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsMarketNewsReq.ProtoReflect.Descriptor instead.
func (*NewsMarketNewsReq) Descriptor() ([]byte, []int) {
	return file_news_news_msg_proto_rawDescGZIP(), []int{0}
}

type NewsMarketNewsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*DBMarketNews        `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsMarketNewsResp) Reset() {
	*x = NewsMarketNewsResp{}
	mi := &file_news_news_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsMarketNewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsMarketNewsResp) ProtoMessage() {}

func (x *NewsMarketNewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_news_news_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsMarketNewsResp.ProtoReflect.Descriptor instead.
func (*NewsMarketNewsResp) Descriptor() ([]byte, []int) {
	return file_news_news_msg_proto_rawDescGZIP(), []int{1}
}

func (x *NewsMarketNewsResp) GetNews() []*DBMarketNews {
	if x != nil {
		return x.News
	}
	return nil
}

var File_news_news_msg_proto protoreflect.FileDescriptor

const file_news_news_msg_proto_rawDesc = "" +
	"\n" +
	"\x13news/news_msg.proto\x1a\x12news/news_db.proto\"\x13\n" +
	"\x11NewsMarketNewsReq\"7\n" +
	"\x12NewsMarketNewsResp\x12!\n" +
	"\x04news\x18\x01 \x03(\v2\r.DBMarketNewsR\x04newsB\x06Z\x04.;pbb\x06proto3"

var (
	file_news_news_msg_proto_rawDescOnce sync.Once
	file_news_news_msg_proto_rawDescData []byte
)

func file_news_news_msg_proto_rawDescGZIP() []byte {
	file_news_news_msg_proto_rawDescOnce.Do(func() {
		file_news_news_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_news_msg_proto_rawDesc), len(file_news_news_msg_proto_rawDesc)))
	})
	return file_news_news_msg_proto_rawDescData
}

var file_news_news_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_news_news_msg_proto_goTypes = []any{
	(*NewsMarketNewsReq)(nil),  // 0: NewsMarketNewsReq
	(*NewsMarketNewsResp)(nil), // 1: NewsMarketNewsResp
	(*DBMarketNews)(nil),       // 2: DBMarketNews
}
var file_news_news_msg_proto_depIdxs = []int32{
	2, // 0: NewsMarketNewsResp.news:type_name -> DBMarketNews
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_news_news_msg_proto_init() }
func file_news_news_msg_proto_init() {
	if File_news_news_msg_proto != nil {
		return
	}
	file_news_news_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_news_msg_proto_rawDesc), len(file_news_news_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_news_news_msg_proto_goTypes,
		DependencyIndexes: file_news_news_msg_proto_depIdxs,
		MessageInfos:      file_news_news_msg_proto_msgTypes,
	}.Build()
	File_news_news_msg_proto = out.File
	file_news_news_msg_proto_goTypes = nil
	file_news_news_msg_proto_depIdxs = nil
}
