// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stock_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 股票基础信息（静态/半静态）
type DBStockIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`              //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 主键ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_market_symbol"`      //@go_tags(`gorm:"symbol;uniqueIndex:uk_market_symbol" json:"symbol"`) 股票代码
	Market        string                 `protobuf:"bytes,3,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_market_symbol"`      //@go_tags(`gorm:"market;uniqueIndex:uk_market_symbol" json:"market"`) 市场标识(sh/sz)
	Exchange      string                 `protobuf:"bytes,4,opt,name=Exchange,proto3" json:"exchange" gorm:"exchange"`  //@go_tags(`gorm:"exchange" json:"exchange"`) 交易所(SSE/SZSE)
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"name" gorm:"name"`          //@go_tags(`gorm:"name" json:"name"`) 公司简称
	FullName      string                 `protobuf:"bytes,6,opt,name=FullName,proto3" json:"full_name" gorm:"full_name"`  //@go_tags(`gorm:"full_name" json:"full_name"`) 公司全称
	ISIN          string                 `protobuf:"bytes,7,opt,name=ISIN,proto3" json:"isin" gorm:"isin;index"`          //@go_tags(`gorm:"isin;index" json:"isin"`) 国际证券识别码
	Industry      string                 `protobuf:"bytes,8,opt,name=Industry,proto3" json:"industry" gorm:"industry"`  //@go_tags(`gorm:"industry" json:"industry"`) 行业
	Sector        string                 `protobuf:"bytes,9,opt,name=Sector,proto3" json:"sector" gorm:"sector"`      //@go_tags(`gorm:"sector" json:"sector"`) 板块
	Area          string                 `protobuf:"bytes,10,opt,name=Area,proto3" json:"area" gorm:"area"`         //@go_tags(`gorm:"area" json:"area"`) 地区
	Currency      string                 `protobuf:"bytes,11,opt,name=Currency,proto3" json:"currency" gorm:"currency"` //@go_tags(`gorm:"currency" json:"currency"`) 币种
	ListDate      string                 `protobuf:"bytes,12,opt,name=ListDate,proto3" json:"list_date" gorm:"list_date"` //@go_tags(`gorm:"list_date" json:"list_date"`) 上市日期(YYYYMMDD)
	Status        string                 `protobuf:"bytes,13,opt,name=Status,proto3" json:"status" gorm:"status"`     //@go_tags(`gorm:"status" json:"status"`) 上市状态
	Aliases       []string               `protobuf:"bytes,14,rep,name=Aliases,proto3" json:"aliases" gorm:"aliases;serializer:json"`   //@go_tags(`gorm:"aliases;serializer:json" json:"aliases"`) 别名列表
	CreateAt      string                 `protobuf:"bytes,15,opt,name=CreateAt,proto3" json:"create_at" gorm:"create_at"` //@go_tags(`gorm:"create_at" json:"create_at"`) 创建时间
	UpdateAt      string                 `protobuf:"bytes,16,opt,name=UpdateAt,proto3" json:"update_at" gorm:"update_at"` //@go_tags(`gorm:"update_at" json:"update_at"`) 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBStockIdentity) Reset() {
	*x = DBStockIdentity{}
	mi := &file_stock_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBStockIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBStockIdentity) ProtoMessage() {}

func (x *DBStockIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_stock_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBStockIdentity.ProtoReflect.Descriptor instead.
func (*DBStockIdentity) Descriptor() ([]byte, []int) {
	return file_stock_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBStockIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBStockIdentity) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DBStockIdentity) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DBStockIdentity) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *DBStockIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBStockIdentity) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DBStockIdentity) GetISIN() string {
	if x != nil {
		return x.ISIN
	}
	return ""
}

func (x *DBStockIdentity) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *DBStockIdentity) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *DBStockIdentity) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *DBStockIdentity) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DBStockIdentity) GetListDate() string {
	if x != nil {
		return x.ListDate
	}
	return ""
}

func (x *DBStockIdentity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DBStockIdentity) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *DBStockIdentity) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *DBStockIdentity) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

// 日/周/月K线（行情）
type DBStockBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`                  //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 主键ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_symbol_tf_ts"`          //@go_tags(`gorm:"symbol;uniqueIndex:uk_symbol_tf_ts" json:"symbol"`) 股票代码
	Market        string                 `protobuf:"bytes,3,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_symbol_tf_ts"`          //@go_tags(`gorm:"market;uniqueIndex:uk_symbol_tf_ts" json:"market"`) 市场标识
	Timeframe     string                 `protobuf:"bytes,4,opt,name=Timeframe,proto3" json:"timeframe" gorm:"timeframe;uniqueIndex:uk_symbol_tf_ts"`    //@go_tags(`gorm:"timeframe;uniqueIndex:uk_symbol_tf_ts" json:"timeframe"`) 周期(1d/1w/1mo)
	Ts            string                 `protobuf:"bytes,5,opt,name=Ts,proto3" json:"ts" gorm:"ts;uniqueIndex:uk_symbol_tf_ts"`                  //@go_tags(`gorm:"ts;uniqueIndex:uk_symbol_tf_ts" json:"ts"`) 时间戳(RFC3339)
	Open          float64                `protobuf:"fixed64,6,opt,name=Open,proto3" json:"open" gorm:"open"`            //@go_tags(`gorm:"open" json:"open"`) 开盘价
	High          float64                `protobuf:"fixed64,7,opt,name=High,proto3" json:"high" gorm:"high"`            //@go_tags(`gorm:"high" json:"high"`) 最高价
	Low           float64                `protobuf:"fixed64,8,opt,name=Low,proto3" json:"low" gorm:"low"`              //@go_tags(`gorm:"low" json:"low"`) 最低价
	Close         float64                `protobuf:"fixed64,9,opt,name=Close,proto3" json:"close" gorm:"close"`          //@go_tags(`gorm:"close" json:"close"`) 收盘价
	Volume        int64                  `protobuf:"varint,10,opt,name=Volume,proto3" json:"volume" gorm:"volume"`        //@go_tags(`gorm:"volume" json:"volume"`) 成交量(股)
	Turnover      float64                `protobuf:"fixed64,11,opt,name=Turnover,proto3" json:"turnover" gorm:"turnover"`   //@go_tags(`gorm:"turnover" json:"turnover"`) 成交额(货币)
	AdjFactor     float64                `protobuf:"fixed64,12,opt,name=AdjFactor,proto3" json:"adj_factor" gorm:"adj_factor"` //@go_tags(`gorm:"adj_factor" json:"adj_factor"`) 复权因子
	Source        string                 `protobuf:"bytes,13,opt,name=Source,proto3" json:"source" gorm:"source"`         //@go_tags(`gorm:"source" json:"source"`) 数据来源(akshare等)
	CreateAt      string                 `protobuf:"bytes,14,opt,name=CreateAt,proto3" json:"create_at" gorm:"create_at"`     //@go_tags(`gorm:"create_at" json:"create_at"`) 创建时间
	UpdateAt      string                 `protobuf:"bytes,15,opt,name=UpdateAt,proto3" json:"update_at" gorm:"update_at"`     //@go_tags(`gorm:"update_at" json:"update_at"`) 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBStockBar) Reset() {
	*x = DBStockBar{}
	mi := &file_stock_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBStockBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBStockBar) ProtoMessage() {}

func (x *DBStockBar) ProtoReflect() protoreflect.Message {
	mi := &file_stock_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBStockBar.ProtoReflect.Descriptor instead.
func (*DBStockBar) Descriptor() ([]byte, []int) {
	return file_stock_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBStockBar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBStockBar) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DBStockBar) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DBStockBar) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *DBStockBar) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *DBStockBar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *DBStockBar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *DBStockBar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *DBStockBar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *DBStockBar) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *DBStockBar) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *DBStockBar) GetAdjFactor() float64 {
	if x != nil {
		return x.AdjFactor
	}
	return 0
}

func (x *DBStockBar) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DBStockBar) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *DBStockBar) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

// 基本面快照（按期/按时间）
type DBFundamentalSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`                                                                                        //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 主键ID
	Symbol           string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_symbol_ts"`                                                                                //@go_tags(`gorm:"symbol;uniqueIndex:uk_symbol_ts" json:"symbol"`) 股票代码
	Market           string                 `protobuf:"bytes,3,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_symbol_ts"`                                                                                //@go_tags(`gorm:"market;uniqueIndex:uk_symbol_ts" json:"market"`) 市场标识
	Ts               string                 `protobuf:"bytes,4,opt,name=Ts,proto3" json:"ts" gorm:"ts;uniqueIndex:uk_symbol_ts"`                                                                                        //@go_tags(`gorm:"ts;uniqueIndex:uk_symbol_ts" json:"ts"`) 时间戳(RFC3339)
	Period           string                 `protobuf:"bytes,5,opt,name=Period,proto3" json:"period" gorm:"period"`                                                                                //@go_tags(`gorm:"period" json:"period"`) 周期（如 FY/Q）
	FiscalYear       string                 `protobuf:"bytes,6,opt,name=FiscalYear,proto3" json:"fiscal_year" gorm:"fiscal_year"`                                                                        //@go_tags(`gorm:"fiscal_year" json:"fiscal_year"`) 财年
	FiscalQuarter    string                 `protobuf:"bytes,7,opt,name=FiscalQuarter,proto3" json:"fiscal_quarter" gorm:"fiscal_quarter"`                                                                  //@go_tags(`gorm:"fiscal_quarter" json:"fiscal_quarter"`) 财季
	Source           string                 `protobuf:"bytes,8,opt,name=Source,proto3" json:"source" gorm:"source"`                                                                                //@go_tags(`gorm:"source" json:"source"`) 数据来源
	Revenue          float64                `protobuf:"fixed64,20,opt,name=Revenue,proto3" json:"revenue" gorm:"revenue"`                                                                           //@go_tags(`gorm:"revenue" json:"revenue"`) 营业收入
	OperatingIncome  float64                `protobuf:"fixed64,21,opt,name=OperatingIncome,proto3" json:"operating_income" gorm:"operating_income"`                                                           //@go_tags(`gorm:"operating_income" json:"operating_income"`) 营业利润
	NetProfit        float64                `protobuf:"fixed64,22,opt,name=NetProfit,proto3" json:"net_profit" gorm:"net_profit"`                                                                       //@go_tags(`gorm:"net_profit" json:"net_profit"`) 净利润
	EPS              float64                `protobuf:"fixed64,23,opt,name=EPS,proto3" json:"eps" gorm:"eps"`                                                                                   //@go_tags(`gorm:"eps" json:"eps"`) 每股收益
	ROE              float64                `protobuf:"fixed64,24,opt,name=ROE,proto3" json:"roe" gorm:"roe"`                                                                                   //@go_tags(`gorm:"roe" json:"roe"`) 净资产收益率
	ROA              float64                `protobuf:"fixed64,25,opt,name=ROA,proto3" json:"roa" gorm:"roa"`                                                                                   //@go_tags(`gorm:"roa" json:"roa"`) 总资产收益率
	GrossMargin      float64                `protobuf:"fixed64,26,opt,name=GrossMargin,proto3" json:"gross_margin" gorm:"gross_margin"`                                                                   //@go_tags(`gorm:"gross_margin" json:"gross_margin"`) 毛利率
	OperatingMargin  float64                `protobuf:"fixed64,27,opt,name=OperatingMargin,proto3" json:"operating_margin" gorm:"operating_margin"`                                                           //@go_tags(`gorm:"operating_margin" json:"operating_margin"`) 营业利润率
	NetMargin        float64                `protobuf:"fixed64,28,opt,name=NetMargin,proto3" json:"net_margin" gorm:"net_margin"`                                                                       //@go_tags(`gorm:"net_margin" json:"net_margin"`) 净利率
	PE               float64                `protobuf:"fixed64,29,opt,name=PE,proto3" json:"pe" gorm:"pe"`                                                                                     //@go_tags(`gorm:"pe" json:"pe"`) 市盈率
	PB               float64                `protobuf:"fixed64,30,opt,name=PB,proto3" json:"pb" gorm:"pb"`                                                                                     //@go_tags(`gorm:"pb" json:"pb"`) 市净率
	PS               float64                `protobuf:"fixed64,31,opt,name=PS,proto3" json:"ps" gorm:"ps"`                                                                                     //@go_tags(`gorm:"ps" json:"ps"`) 市销率
	DividendPerShare float64                `protobuf:"fixed64,32,opt,name=DividendPerShare,proto3" json:"dividend_per_share" gorm:"dividend_per_share"`                                                         //@go_tags(`gorm:"dividend_per_share" json:"dividend_per_share"`) 每股分红
	DividendYield    float64                `protobuf:"fixed64,33,opt,name=DividendYield,proto3" json:"dividend_yield" gorm:"dividend_yield"`                                                               //@go_tags(`gorm:"dividend_yield" json:"dividend_yield"`) 股息率
	FreeCashFlow     float64                `protobuf:"fixed64,34,opt,name=FreeCashFlow,proto3" json:"free_cash_flow" gorm:"free_cash_flow"`                                                                 //@go_tags(`gorm:"free_cash_flow" json:"free_cash_flow"`) 自由现金流
	DebtToEquity     float64                `protobuf:"fixed64,35,opt,name=DebtToEquity,proto3" json:"debt_to_equity" gorm:"debt_to_equity"`                                                                 //@go_tags(`gorm:"debt_to_equity" json:"debt_to_equity"`) 资产负债比
	CurrentRatio     float64                `protobuf:"fixed64,36,opt,name=CurrentRatio,proto3" json:"current_ratio" gorm:"current_ratio"`                                                                 //@go_tags(`gorm:"current_ratio" json:"current_ratio"`) 流动比率
	QuickRatio       float64                `protobuf:"fixed64,37,opt,name=QuickRatio,proto3" json:"quick_ratio" gorm:"quick_ratio"`                                                                     //@go_tags(`gorm:"quick_ratio" json:"quick_ratio"`) 速动比率
	TotalAssets      float64                `protobuf:"fixed64,38,opt,name=TotalAssets,proto3" json:"total_assets" gorm:"total_assets"`                                                                   //@go_tags(`gorm:"total_assets" json:"total_assets"`) 总资产
	TotalLiabilities float64                `protobuf:"fixed64,39,opt,name=TotalLiabilities,proto3" json:"total_liabilities" gorm:"total_liabilities"`                                                         //@go_tags(`gorm:"total_liabilities" json:"total_liabilities"`) 总负债
	Equity           float64                `protobuf:"fixed64,40,opt,name=Equity,proto3" json:"equity" gorm:"equity"`                                                                             //@go_tags(`gorm:"equity" json:"equity"`) 股东权益
	RevenueYoY       float64                `protobuf:"fixed64,41,opt,name=RevenueYoY,proto3" json:"revenue_yoy" gorm:"revenue_yoy"`                                                                     //@go_tags(`gorm:"revenue_yoy" json:"revenue_yoy"`) 收入同比
	NetProfitYoY     float64                `protobuf:"fixed64,42,opt,name=NetProfitYoY,proto3" json:"net_profit_yoy" gorm:"net_profit_yoy"`                                                                 //@go_tags(`gorm:"net_profit_yoy" json:"net_profit_yoy"`) 净利润同比
	EPSYoY           float64                `protobuf:"fixed64,43,opt,name=EPSYoY,proto3" json:"eps_yoy" gorm:"eps_yoy"`                                                                             //@go_tags(`gorm:"eps_yoy" json:"eps_yoy"`) EPS 同比
	Metrics          map[string]float64     `protobuf:"bytes,60,rep,name=Metrics,proto3" json:"metrics" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value" gorm:"metrics;serializer:json"` //@go_tags(`gorm:"metrics;serializer:json" json:"metrics"`) 自定义扩展指标
	CreateAt         string                 `protobuf:"bytes,61,opt,name=CreateAt,proto3" json:"create_at" gorm:"create_at"`                                                                           //@go_tags(`gorm:"create_at" json:"create_at"`) 创建时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DBFundamentalSnapshot) Reset() {
	*x = DBFundamentalSnapshot{}
	mi := &file_stock_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBFundamentalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBFundamentalSnapshot) ProtoMessage() {}

func (x *DBFundamentalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_stock_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBFundamentalSnapshot.ProtoReflect.Descriptor instead.
func (*DBFundamentalSnapshot) Descriptor() ([]byte, []int) {
	return file_stock_db_proto_rawDescGZIP(), []int{2}
}

func (x *DBFundamentalSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetFiscalYear() string {
	if x != nil {
		return x.FiscalYear
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetFiscalQuarter() string {
	if x != nil {
		return x.FiscalQuarter
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DBFundamentalSnapshot) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetOperatingIncome() float64 {
	if x != nil {
		return x.OperatingIncome
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetNetProfit() float64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetEPS() float64 {
	if x != nil {
		return x.EPS
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetROE() float64 {
	if x != nil {
		return x.ROE
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetROA() float64 {
	if x != nil {
		return x.ROA
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetGrossMargin() float64 {
	if x != nil {
		return x.GrossMargin
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetOperatingMargin() float64 {
	if x != nil {
		return x.OperatingMargin
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetNetMargin() float64 {
	if x != nil {
		return x.NetMargin
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetPE() float64 {
	if x != nil {
		return x.PE
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetPB() float64 {
	if x != nil {
		return x.PB
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetPS() float64 {
	if x != nil {
		return x.PS
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetDividendPerShare() float64 {
	if x != nil {
		return x.DividendPerShare
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetDividendYield() float64 {
	if x != nil {
		return x.DividendYield
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetFreeCashFlow() float64 {
	if x != nil {
		return x.FreeCashFlow
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetDebtToEquity() float64 {
	if x != nil {
		return x.DebtToEquity
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetCurrentRatio() float64 {
	if x != nil {
		return x.CurrentRatio
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetQuickRatio() float64 {
	if x != nil {
		return x.QuickRatio
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetTotalAssets() float64 {
	if x != nil {
		return x.TotalAssets
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetTotalLiabilities() float64 {
	if x != nil {
		return x.TotalLiabilities
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetRevenueYoY() float64 {
	if x != nil {
		return x.RevenueYoY
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetNetProfitYoY() float64 {
	if x != nil {
		return x.NetProfitYoY
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetEPSYoY() float64 {
	if x != nil {
		return x.EPSYoY
	}
	return 0
}

func (x *DBFundamentalSnapshot) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DBFundamentalSnapshot) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

// 股票新闻
type DBStockNews struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`             //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 主键ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_symbol_ts"`     //@go_tags(`gorm:"symbol;uniqueIndex:uk_symbol_ts" json:"symbol"`) 股票代码
	Market        string                 `protobuf:"bytes,3,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_symbol_ts"`     //@go_tags(`gorm:"market;uniqueIndex:uk_symbol_ts" json:"market"`) 市场标识
	Ts            string                 `protobuf:"bytes,4,opt,name=Ts,proto3" json:"ts" gorm:"ts;uniqueIndex:uk_symbol_ts"`             //@go_tags(`gorm:"ts;uniqueIndex:uk_symbol_ts" json:"ts"`) 时间戳(RFC3339)
	Title         string                 `protobuf:"bytes,5,opt,name=Title,proto3" json:"title" gorm:"title"`       //@go_tags(`gorm:"title" json:"title"`) 新闻标题
	Source        string                 `protobuf:"bytes,6,opt,name=Source,proto3" json:"source" gorm:"source"`     //@go_tags(`gorm:"source" json:"source"`) 数据来源
	CreateAt      string                 `protobuf:"bytes,7,opt,name=CreateAt,proto3" json:"create_at" gorm:"create_at"` //@go_tags(`gorm:"create_at" json:"create_at"`) 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBStockNews) Reset() {
	*x = DBStockNews{}
	mi := &file_stock_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBStockNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBStockNews) ProtoMessage() {}

func (x *DBStockNews) ProtoReflect() protoreflect.Message {
	mi := &file_stock_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBStockNews.ProtoReflect.Descriptor instead.
func (*DBStockNews) Descriptor() ([]byte, []int) {
	return file_stock_db_proto_rawDescGZIP(), []int{3}
}

func (x *DBStockNews) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBStockNews) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DBStockNews) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DBStockNews) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *DBStockNews) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DBStockNews) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DBStockNews) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

// 股票分析报告 每日
type DBStockReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"id" gorm:"id;primaryKey;autoIncrement"`             //@go_tags(`gorm:"id;primaryKey;autoIncrement" json:"id"`) 主键ID
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"symbol" gorm:"symbol;uniqueIndex:uk_symbol_ts"`     //@go_tags(`gorm:"symbol;uniqueIndex:uk_symbol_ts" json:"symbol"`) 股票代码
	Market        string                 `protobuf:"bytes,3,opt,name=Market,proto3" json:"market" gorm:"market;uniqueIndex:uk_symbol_ts"`     //@go_tags(`gorm:"market;uniqueIndex:uk_symbol_ts" json:"market"`) 市场标识
	Ts            string                 `protobuf:"bytes,4,opt,name=Ts,proto3" json:"ts" gorm:"ts;uniqueIndex:uk_symbol_ts"`             //@go_tags(`gorm:"ts;uniqueIndex:uk_symbol_ts" json:"ts"`) 时间戳(RFC3339)
	Source        string                 `protobuf:"bytes,5,opt,name=Source,proto3" json:"source" gorm:"source"`     //@go_tags(`gorm:"source" json:"source"`) 数据来源
	CreateAt      string                 `protobuf:"bytes,6,opt,name=CreateAt,proto3" json:"create_at" gorm:"create_at"` //@go_tags(`gorm:"create_at" json:"create_at"`) 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBStockReport) Reset() {
	*x = DBStockReport{}
	mi := &file_stock_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBStockReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBStockReport) ProtoMessage() {}

func (x *DBStockReport) ProtoReflect() protoreflect.Message {
	mi := &file_stock_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBStockReport.ProtoReflect.Descriptor instead.
func (*DBStockReport) Descriptor() ([]byte, []int) {
	return file_stock_db_proto_rawDescGZIP(), []int{4}
}

func (x *DBStockReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBStockReport) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DBStockReport) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DBStockReport) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *DBStockReport) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DBStockReport) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

var File_stock_db_proto protoreflect.FileDescriptor

const file_stock_db_proto_rawDesc = "" +
	"\n" +
	"\x0estock_db.proto\"\x9b\x03\n" +
	"\x0fDBStockIdentity\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x16\n" +
	"\x06Market\x18\x03 \x01(\tR\x06Market\x12\x1a\n" +
	"\bExchange\x18\x04 \x01(\tR\bExchange\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFullName\x18\x06 \x01(\tR\bFullName\x12\x12\n" +
	"\x04ISIN\x18\a \x01(\tR\x04ISIN\x12\x1a\n" +
	"\bIndustry\x18\b \x01(\tR\bIndustry\x12\x16\n" +
	"\x06Sector\x18\t \x01(\tR\x06Sector\x12\x12\n" +
	"\x04Area\x18\n" +
	" \x01(\tR\x04Area\x12\x1a\n" +
	"\bCurrency\x18\v \x01(\tR\bCurrency\x12\x1a\n" +
	"\bListDate\x18\f \x01(\tR\bListDate\x12\x16\n" +
	"\x06Status\x18\r \x01(\tR\x06Status\x12\x18\n" +
	"\aAliases\x18\x0e \x03(\tR\aAliases\x12\x1a\n" +
	"\bCreateAt\x18\x0f \x01(\tR\bCreateAt\x12\x1a\n" +
	"\bUpdateAt\x18\x10 \x01(\tR\bUpdateAt\"\xec\x02\n" +
	"\n" +
	"DBStockBar\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x16\n" +
	"\x06Market\x18\x03 \x01(\tR\x06Market\x12\x1c\n" +
	"\tTimeframe\x18\x04 \x01(\tR\tTimeframe\x12\x0e\n" +
	"\x02Ts\x18\x05 \x01(\tR\x02Ts\x12\x12\n" +
	"\x04Open\x18\x06 \x01(\x01R\x04Open\x12\x12\n" +
	"\x04High\x18\a \x01(\x01R\x04High\x12\x10\n" +
	"\x03Low\x18\b \x01(\x01R\x03Low\x12\x14\n" +
	"\x05Close\x18\t \x01(\x01R\x05Close\x12\x16\n" +
	"\x06Volume\x18\n" +
	" \x01(\x03R\x06Volume\x12\x1a\n" +
	"\bTurnover\x18\v \x01(\x01R\bTurnover\x12\x1c\n" +
	"\tAdjFactor\x18\f \x01(\x01R\tAdjFactor\x12\x16\n" +
	"\x06Source\x18\r \x01(\tR\x06Source\x12\x1a\n" +
	"\bCreateAt\x18\x0e \x01(\tR\bCreateAt\x12\x1a\n" +
	"\bUpdateAt\x18\x0f \x01(\tR\bUpdateAt\"\xc6\b\n" +
	"\x15DBFundamentalSnapshot\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x16\n" +
	"\x06Market\x18\x03 \x01(\tR\x06Market\x12\x0e\n" +
	"\x02Ts\x18\x04 \x01(\tR\x02Ts\x12\x16\n" +
	"\x06Period\x18\x05 \x01(\tR\x06Period\x12\x1e\n" +
	"\n" +
	"FiscalYear\x18\x06 \x01(\tR\n" +
	"FiscalYear\x12$\n" +
	"\rFiscalQuarter\x18\a \x01(\tR\rFiscalQuarter\x12\x16\n" +
	"\x06Source\x18\b \x01(\tR\x06Source\x12\x18\n" +
	"\aRevenue\x18\x14 \x01(\x01R\aRevenue\x12(\n" +
	"\x0fOperatingIncome\x18\x15 \x01(\x01R\x0fOperatingIncome\x12\x1c\n" +
	"\tNetProfit\x18\x16 \x01(\x01R\tNetProfit\x12\x10\n" +
	"\x03EPS\x18\x17 \x01(\x01R\x03EPS\x12\x10\n" +
	"\x03ROE\x18\x18 \x01(\x01R\x03ROE\x12\x10\n" +
	"\x03ROA\x18\x19 \x01(\x01R\x03ROA\x12 \n" +
	"\vGrossMargin\x18\x1a \x01(\x01R\vGrossMargin\x12(\n" +
	"\x0fOperatingMargin\x18\x1b \x01(\x01R\x0fOperatingMargin\x12\x1c\n" +
	"\tNetMargin\x18\x1c \x01(\x01R\tNetMargin\x12\x0e\n" +
	"\x02PE\x18\x1d \x01(\x01R\x02PE\x12\x0e\n" +
	"\x02PB\x18\x1e \x01(\x01R\x02PB\x12\x0e\n" +
	"\x02PS\x18\x1f \x01(\x01R\x02PS\x12*\n" +
	"\x10DividendPerShare\x18  \x01(\x01R\x10DividendPerShare\x12$\n" +
	"\rDividendYield\x18! \x01(\x01R\rDividendYield\x12\"\n" +
	"\fFreeCashFlow\x18\" \x01(\x01R\fFreeCashFlow\x12\"\n" +
	"\fDebtToEquity\x18# \x01(\x01R\fDebtToEquity\x12\"\n" +
	"\fCurrentRatio\x18$ \x01(\x01R\fCurrentRatio\x12\x1e\n" +
	"\n" +
	"QuickRatio\x18% \x01(\x01R\n" +
	"QuickRatio\x12 \n" +
	"\vTotalAssets\x18& \x01(\x01R\vTotalAssets\x12*\n" +
	"\x10TotalLiabilities\x18' \x01(\x01R\x10TotalLiabilities\x12\x16\n" +
	"\x06Equity\x18( \x01(\x01R\x06Equity\x12\x1e\n" +
	"\n" +
	"RevenueYoY\x18) \x01(\x01R\n" +
	"RevenueYoY\x12\"\n" +
	"\fNetProfitYoY\x18* \x01(\x01R\fNetProfitYoY\x12\x16\n" +
	"\x06EPSYoY\x18+ \x01(\x01R\x06EPSYoY\x12=\n" +
	"\aMetrics\x18< \x03(\v2#.DBFundamentalSnapshot.MetricsEntryR\aMetrics\x12\x1a\n" +
	"\bCreateAt\x18= \x01(\tR\bCreateAt\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xa7\x01\n" +
	"\vDBStockNews\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x16\n" +
	"\x06Market\x18\x03 \x01(\tR\x06Market\x12\x0e\n" +
	"\x02Ts\x18\x04 \x01(\tR\x02Ts\x12\x14\n" +
	"\x05Title\x18\x05 \x01(\tR\x05Title\x12\x16\n" +
	"\x06Source\x18\x06 \x01(\tR\x06Source\x12\x1a\n" +
	"\bCreateAt\x18\a \x01(\tR\bCreateAt\"\x93\x01\n" +
	"\rDBStockReport\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x16\n" +
	"\x06Market\x18\x03 \x01(\tR\x06Market\x12\x0e\n" +
	"\x02Ts\x18\x04 \x01(\tR\x02Ts\x12\x16\n" +
	"\x06Source\x18\x05 \x01(\tR\x06Source\x12\x1a\n" +
	"\bCreateAt\x18\x06 \x01(\tR\bCreateAtB\x06Z\x04.;pbb\x06proto3"

var (
	file_stock_db_proto_rawDescOnce sync.Once
	file_stock_db_proto_rawDescData []byte
)

func file_stock_db_proto_rawDescGZIP() []byte {
	file_stock_db_proto_rawDescOnce.Do(func() {
		file_stock_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_db_proto_rawDesc), len(file_stock_db_proto_rawDesc)))
	})
	return file_stock_db_proto_rawDescData
}

var file_stock_db_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_db_proto_goTypes = []any{
	(*DBStockIdentity)(nil),       // 0: DBStockIdentity
	(*DBStockBar)(nil),            // 1: DBStockBar
	(*DBFundamentalSnapshot)(nil), // 2: DBFundamentalSnapshot
	(*DBStockNews)(nil),           // 3: DBStockNews
	(*DBStockReport)(nil),         // 4: DBStockReport
	nil,                           // 5: DBFundamentalSnapshot.MetricsEntry
}
var file_stock_db_proto_depIdxs = []int32{
	5, // 0: DBFundamentalSnapshot.Metrics:type_name -> DBFundamentalSnapshot.MetricsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_db_proto_init() }
func file_stock_db_proto_init() {
	if File_stock_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_db_proto_rawDesc), len(file_stock_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_db_proto_goTypes,
		DependencyIndexes: file_stock_db_proto_depIdxs,
		MessageInfos:      file_stock_db_proto_msgTypes,
	}.Build()
	File_stock_db_proto = out.File
	file_stock_db_proto_goTypes = nil
	file_stock_db_proto_depIdxs = nil
}
