// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stock/stock_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取对应股票的实时数据
type StockGetRealTimeDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetRealTimeDataReq) Reset() {
	*x = StockGetRealTimeDataReq{}
	mi := &file_stock_stock_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetRealTimeDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataReq) ProtoMessage() {}

func (x *StockGetRealTimeDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataReq.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{0}
}

func (x *StockGetRealTimeDataReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type StockGetRealTimeDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DBStockRealTimeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetRealTimeDataResp) Reset() {
	*x = StockGetRealTimeDataResp{}
	mi := &file_stock_stock_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetRealTimeDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataResp) ProtoMessage() {}

func (x *StockGetRealTimeDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataResp.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{1}
}

func (x *StockGetRealTimeDataResp) GetItems() []*DBStockRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取股票信息请求
type StockGetInfosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockIds      []string               `protobuf:"bytes,1,rep,name=stock_ids,json=stockIds,proto3" json:"stock_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetInfosReq) Reset() {
	*x = StockGetInfosReq{}
	mi := &file_stock_stock_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetIntradayChartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetIntradayChartReq) ProtoMessage() {}

func (x *StockGetIntradayChartReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetIntradayChartReq.ProtoReflect.Descriptor instead.
func (*StockGetIntradayChartReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{2}
}

func (x *StockGetIntradayChartReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StockGetInfosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockInfos    []*DBStockIdentity     `protobuf:"bytes,1,rep,name=stock_infos,json=stockInfos,proto3" json:"stock_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetInfosResp) Reset() {
	*x = StockGetInfosResp{}
	mi := &file_stock_stock_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetIntradayChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetIntradayChartResp) ProtoMessage() {}

func (x *StockGetIntradayChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetIntradayChartResp.ProtoReflect.Descriptor instead.
func (*StockGetIntradayChartResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{3}
}

func (x *StockGetIntradayChartResp) GetItems() []*DBStockRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取基本面快照请求
type StockGetFundamentalSnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetFundamentalSnapshotReq) Reset() {
	*x = StockGetFundamentalSnapshotReq{}
	mi := &file_stock_stock_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetBasicInfoReq) ProtoMessage() {}

func (x *StockGetBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetBasicInfoReq.ProtoReflect.Descriptor instead.
func (*StockGetBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{4}
}

func (x *StockGetBasicInfoReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StockGetFundamentalSnapshotResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Snapshots     []*DBFundamentalSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockGetFundamentalSnapshotResp) Reset() {
	*x = StockGetFundamentalSnapshotResp{}
	mi := &file_stock_stock_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockGetBasicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetBasicInfoResp) ProtoMessage() {}

func (x *StockGetBasicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetBasicInfoResp.ProtoReflect.Descriptor instead.
func (*StockGetBasicInfoResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{5}
}

func (x *StockGetBasicInfoResp) GetInfo() *DBStockBasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 获取股票的经营快照
type StockGetOperatingSnapshotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *StockGetOperatingSnapshotReq) Reset() {
	*x = StockGetOperatingSnapshotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetOperatingSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetOperatingSnapshotReq) ProtoMessage() {}

func (x *StockGetOperatingSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetOperatingSnapshotReq.ProtoReflect.Descriptor instead.
func (*StockGetOperatingSnapshotReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{6}
}

func (x *StockGetOperatingSnapshotReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StockGetOperatingSnapshotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshots []*DBStockOperatingSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
}

func (x *StockGetOperatingSnapshotResp) Reset() {
	*x = StockGetOperatingSnapshotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetOperatingSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetOperatingSnapshotResp) ProtoMessage() {}

func (x *StockGetOperatingSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetOperatingSnapshotResp.ProtoReflect.Descriptor instead.
func (*StockGetOperatingSnapshotResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{7}
}

func (x *StockGetOperatingSnapshotResp) GetSnapshots() []*DBStockOperatingSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_stock_stock_msg_proto protoreflect.FileDescriptor

const file_stock_stock_msg_proto_rawDesc = "" +
	"\n" +
	"\x15stock/stock_msg.proto\x1a\x14stock/stock_db.proto\"/\n" +
	"\x17StockGetRealTimeDataReq\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"F\n" +
	"\x18StockGetRealTimeDataResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.DBStockRealTimeItemR\x05items\"/\n" +
	"\x10StockGetInfosReq\x12\x1b\n" +
	"\tstock_ids\x18\x01 \x03(\tR\bstockIds\"F\n" +
	"\x11StockGetInfosResp\x121\n" +
	"\vstock_infos\x18\x01 \x03(\v2\x10.DBStockIdentityR\n" +
	"stockInfos\"0\n" +
	"\x1eStockGetFundamentalSnapshotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x1fStockGetFundamentalSnapshotResp\x124\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x16.DBFundamentalSnapshotR\tsnapshotsB\x06Z\x04.;pbb\x06proto3"

var (
	file_stock_stock_msg_proto_rawDescOnce sync.Once
	file_stock_stock_msg_proto_rawDescData []byte
)

func file_stock_stock_msg_proto_rawDescGZIP() []byte {
	file_stock_stock_msg_proto_rawDescOnce.Do(func() {
		file_stock_stock_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_stock_msg_proto_rawDesc), len(file_stock_stock_msg_proto_rawDesc)))
	})
	return file_stock_stock_msg_proto_rawDescData
}

var file_stock_stock_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_stock_msg_proto_goTypes = []any{
	(*StockGetRealTimeDataReq)(nil),         // 0: StockGetRealTimeDataReq
	(*StockGetRealTimeDataResp)(nil),        // 1: StockGetRealTimeDataResp
	(*StockGetInfosReq)(nil),                // 2: StockGetInfosReq
	(*StockGetInfosResp)(nil),               // 3: StockGetInfosResp
	(*StockGetFundamentalSnapshotReq)(nil),  // 4: StockGetFundamentalSnapshotReq
	(*StockGetFundamentalSnapshotResp)(nil), // 5: StockGetFundamentalSnapshotResp
	(*DBStockRealTimeItem)(nil),             // 6: DBStockRealTimeItem
	(*DBStockIdentity)(nil),                 // 7: DBStockIdentity
	(*DBFundamentalSnapshot)(nil),           // 8: DBFundamentalSnapshot
}
var file_stock_stock_msg_proto_depIdxs = []int32{
	8,  // 0: StockGetRealTimeDataResp.items:type_name -> DBStockRealTimeItem
	8,  // 1: StockGetIntradayChartResp.items:type_name -> DBStockRealTimeItem
	9,  // 2: StockGetBasicInfoResp.info:type_name -> DBStockBasicInfo
	10, // 3: StockGetOperatingSnapshotResp.snapshots:type_name -> DBStockOperatingSnapshot
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_stock_stock_msg_proto_init() }
func file_stock_stock_msg_proto_init() {
	if File_stock_stock_msg_proto != nil {
		return
	}
	file_stock_stock_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_stock_msg_proto_rawDesc), len(file_stock_stock_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_stock_msg_proto_goTypes,
		DependencyIndexes: file_stock_stock_msg_proto_depIdxs,
		MessageInfos:      file_stock_stock_msg_proto_msgTypes,
	}.Build()
	File_stock_stock_msg_proto = out.File
	file_stock_stock_msg_proto_goTypes = nil
	file_stock_stock_msg_proto_depIdxs = nil
}
