// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: stock/stock_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//获取对应股票的实时数据
type StockGetRealTimeDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *StockGetRealTimeDataReq) Reset() {
	*x = StockGetRealTimeDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetRealTimeDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataReq) ProtoMessage() {}

func (x *StockGetRealTimeDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataReq.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{0}
}

func (x *StockGetRealTimeDataReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type StockGetRealTimeDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DBStockRealTimeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StockGetRealTimeDataResp) Reset() {
	*x = StockGetRealTimeDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetRealTimeDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataResp) ProtoMessage() {}

func (x *StockGetRealTimeDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataResp.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{1}
}

func (x *StockGetRealTimeDataResp) GetItems() []*DBStockRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取股票信息请求
type StockGetInfosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockIds []string `protobuf:"bytes,1,rep,name=stock_ids,json=stockIds,proto3" json:"stock_ids,omitempty"`
}

func (x *StockGetInfosReq) Reset() {
	*x = StockGetInfosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetInfosReq) ProtoMessage() {}

func (x *StockGetInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetInfosReq.ProtoReflect.Descriptor instead.
func (*StockGetInfosReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{2}
}

func (x *StockGetInfosReq) GetStockIds() []string {
	if x != nil {
		return x.StockIds
	}
	return nil
}

type StockGetInfosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockInfos []*DBStockIdentity `protobuf:"bytes,1,rep,name=stock_infos,json=stockInfos,proto3" json:"stock_infos,omitempty"`
}

func (x *StockGetInfosResp) Reset() {
	*x = StockGetInfosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetInfosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetInfosResp) ProtoMessage() {}

func (x *StockGetInfosResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetInfosResp.ProtoReflect.Descriptor instead.
func (*StockGetInfosResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{3}
}

func (x *StockGetInfosResp) GetStockInfos() []*DBStockIdentity {
	if x != nil {
		return x.StockInfos
	}
	return nil
}

// 获取基本面快照请求
type StockGetFundamentalSnapshotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StockGetFundamentalSnapshotReq) Reset() {
	*x = StockGetFundamentalSnapshotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetFundamentalSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetFundamentalSnapshotReq) ProtoMessage() {}

func (x *StockGetFundamentalSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetFundamentalSnapshotReq.ProtoReflect.Descriptor instead.
func (*StockGetFundamentalSnapshotReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{4}
}

func (x *StockGetFundamentalSnapshotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StockGetFundamentalSnapshotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshots []*DBFundamentalSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
}

func (x *StockGetFundamentalSnapshotResp) Reset() {
	*x = StockGetFundamentalSnapshotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetFundamentalSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetFundamentalSnapshotResp) ProtoMessage() {}

func (x *StockGetFundamentalSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetFundamentalSnapshotResp.ProtoReflect.Descriptor instead.
func (*StockGetFundamentalSnapshotResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{5}
}

func (x *StockGetFundamentalSnapshotResp) GetSnapshots() []*DBFundamentalSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_stock_stock_msg_proto protoreflect.FileDescriptor

var file_stock_stock_msg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x73,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a,
	0x17, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x46,
	0x0a, 0x18, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x42, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0b,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x44, 0x42, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x30, 0x0a, 0x1e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x57, 0x0a, 0x1f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e,
	0x64, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x42, 0x46, 0x75, 0x6e, 0x64,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52,
	0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_stock_msg_proto_rawDescOnce sync.Once
	file_stock_stock_msg_proto_rawDescData = file_stock_stock_msg_proto_rawDesc
)

func file_stock_stock_msg_proto_rawDescGZIP() []byte {
	file_stock_stock_msg_proto_rawDescOnce.Do(func() {
		file_stock_stock_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_stock_msg_proto_rawDescData)
	})
	return file_stock_stock_msg_proto_rawDescData
}

var file_stock_stock_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_stock_msg_proto_goTypes = []interface{}{
	(*StockGetRealTimeDataReq)(nil),         // 0: StockGetRealTimeDataReq
	(*StockGetRealTimeDataResp)(nil),        // 1: StockGetRealTimeDataResp
	(*StockGetInfosReq)(nil),                // 2: StockGetInfosReq
	(*StockGetInfosResp)(nil),               // 3: StockGetInfosResp
	(*StockGetFundamentalSnapshotReq)(nil),  // 4: StockGetFundamentalSnapshotReq
	(*StockGetFundamentalSnapshotResp)(nil), // 5: StockGetFundamentalSnapshotResp
	(*DBStockRealTimeItem)(nil),             // 6: DBStockRealTimeItem
	(*DBStockIdentity)(nil),                 // 7: DBStockIdentity
	(*DBFundamentalSnapshot)(nil),           // 8: DBFundamentalSnapshot
}
var file_stock_stock_msg_proto_depIdxs = []int32{
	6, // 0: StockGetRealTimeDataResp.items:type_name -> DBStockRealTimeItem
	7, // 1: StockGetInfosResp.stock_infos:type_name -> DBStockIdentity
	8, // 2: StockGetFundamentalSnapshotResp.snapshots:type_name -> DBFundamentalSnapshot
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stock_stock_msg_proto_init() }
func file_stock_stock_msg_proto_init() {
	if File_stock_stock_msg_proto != nil {
		return
	}
	file_stock_stock_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stock_stock_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetRealTimeDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetRealTimeDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetInfosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetInfosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetFundamentalSnapshotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetFundamentalSnapshotResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_stock_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_stock_msg_proto_goTypes,
		DependencyIndexes: file_stock_stock_msg_proto_depIdxs,
		MessageInfos:      file_stock_stock_msg_proto_msgTypes,
	}.Build()
	File_stock_stock_msg_proto = out.File
	file_stock_stock_msg_proto_rawDesc = nil
	file_stock_stock_msg_proto_goTypes = nil
	file_stock_stock_msg_proto_depIdxs = nil
}
