// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: stock/stock_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//获取对应股票的实时数据
type StockGetRealTimeDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *StockGetRealTimeDataReq) Reset() {
	*x = StockGetRealTimeDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetRealTimeDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataReq) ProtoMessage() {}

func (x *StockGetRealTimeDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataReq.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{0}
}

func (x *StockGetRealTimeDataReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type StockGetRealTimeDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DBStockRealTimeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StockGetRealTimeDataResp) Reset() {
	*x = StockGetRealTimeDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetRealTimeDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetRealTimeDataResp) ProtoMessage() {}

func (x *StockGetRealTimeDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetRealTimeDataResp.ProtoReflect.Descriptor instead.
func (*StockGetRealTimeDataResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{1}
}

func (x *StockGetRealTimeDataResp) GetItems() []*DBStockRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

//获取股票当日分时数据
type StockGetIntradayChartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *StockGetIntradayChartReq) Reset() {
	*x = StockGetIntradayChartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetIntradayChartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetIntradayChartReq) ProtoMessage() {}

func (x *StockGetIntradayChartReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetIntradayChartReq.ProtoReflect.Descriptor instead.
func (*StockGetIntradayChartReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{2}
}

func (x *StockGetIntradayChartReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

//获取股票当日分时数据响应
type StockGetIntradayChartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DBStockRealTimeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StockGetIntradayChartResp) Reset() {
	*x = StockGetIntradayChartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetIntradayChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetIntradayChartResp) ProtoMessage() {}

func (x *StockGetIntradayChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetIntradayChartResp.ProtoReflect.Descriptor instead.
func (*StockGetIntradayChartResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{3}
}

func (x *StockGetIntradayChartResp) GetItems() []*DBStockRealTimeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 获取股票信息请求
type StockGetBasicInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *StockGetBasicInfoReq) Reset() {
	*x = StockGetBasicInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetBasicInfoReq) ProtoMessage() {}

func (x *StockGetBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetBasicInfoReq.ProtoReflect.Descriptor instead.
func (*StockGetBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{4}
}

func (x *StockGetBasicInfoReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StockGetBasicInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *DBStockBasicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StockGetBasicInfoResp) Reset() {
	*x = StockGetBasicInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetBasicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetBasicInfoResp) ProtoMessage() {}

func (x *StockGetBasicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetBasicInfoResp.ProtoReflect.Descriptor instead.
func (*StockGetBasicInfoResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{5}
}

func (x *StockGetBasicInfoResp) GetInfo() *DBStockBasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 获取股票的经营快照
type StockGetOperatingSnapshotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *StockGetOperatingSnapshotReq) Reset() {
	*x = StockGetOperatingSnapshotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetOperatingSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetOperatingSnapshotReq) ProtoMessage() {}

func (x *StockGetOperatingSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetOperatingSnapshotReq.ProtoReflect.Descriptor instead.
func (*StockGetOperatingSnapshotReq) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{6}
}

func (x *StockGetOperatingSnapshotReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StockGetOperatingSnapshotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshots []*DBStockOperatingSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
}

func (x *StockGetOperatingSnapshotResp) Reset() {
	*x = StockGetOperatingSnapshotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_stock_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockGetOperatingSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockGetOperatingSnapshotResp) ProtoMessage() {}

func (x *StockGetOperatingSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockGetOperatingSnapshotResp.ProtoReflect.Descriptor instead.
func (*StockGetOperatingSnapshotResp) Descriptor() ([]byte, []int) {
	return file_stock_stock_msg_proto_rawDescGZIP(), []int{7}
}

func (x *StockGetOperatingSnapshotResp) GetSnapshots() []*DBStockOperatingSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_stock_stock_msg_proto protoreflect.FileDescriptor

var file_stock_stock_msg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x73,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a,
	0x17, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x46,
	0x0a, 0x18, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x42, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2e, 0x0a, 0x18, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x64, 0x61, 0x79, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x19, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x64, 0x61, 0x79, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x42, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0x2a, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x15, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x42, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x32, 0x0a, 0x1c, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x58, 0x0a, 0x1d, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x37, 0x0a, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x42, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x09,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_stock_msg_proto_rawDescOnce sync.Once
	file_stock_stock_msg_proto_rawDescData = file_stock_stock_msg_proto_rawDesc
)

func file_stock_stock_msg_proto_rawDescGZIP() []byte {
	file_stock_stock_msg_proto_rawDescOnce.Do(func() {
		file_stock_stock_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_stock_msg_proto_rawDescData)
	})
	return file_stock_stock_msg_proto_rawDescData
}

var file_stock_stock_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stock_stock_msg_proto_goTypes = []interface{}{
	(*StockGetRealTimeDataReq)(nil),       // 0: StockGetRealTimeDataReq
	(*StockGetRealTimeDataResp)(nil),      // 1: StockGetRealTimeDataResp
	(*StockGetIntradayChartReq)(nil),      // 2: StockGetIntradayChartReq
	(*StockGetIntradayChartResp)(nil),     // 3: StockGetIntradayChartResp
	(*StockGetBasicInfoReq)(nil),          // 4: StockGetBasicInfoReq
	(*StockGetBasicInfoResp)(nil),         // 5: StockGetBasicInfoResp
	(*StockGetOperatingSnapshotReq)(nil),  // 6: StockGetOperatingSnapshotReq
	(*StockGetOperatingSnapshotResp)(nil), // 7: StockGetOperatingSnapshotResp
	(*DBStockRealTimeItem)(nil),           // 8: DBStockRealTimeItem
	(*DBStockBasicInfo)(nil),              // 9: DBStockBasicInfo
	(*DBStockOperatingSnapshot)(nil),      // 10: DBStockOperatingSnapshot
}
var file_stock_stock_msg_proto_depIdxs = []int32{
	8,  // 0: StockGetRealTimeDataResp.items:type_name -> DBStockRealTimeItem
	8,  // 1: StockGetIntradayChartResp.items:type_name -> DBStockRealTimeItem
	9,  // 2: StockGetBasicInfoResp.info:type_name -> DBStockBasicInfo
	10, // 3: StockGetOperatingSnapshotResp.snapshots:type_name -> DBStockOperatingSnapshot
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_stock_stock_msg_proto_init() }
func file_stock_stock_msg_proto_init() {
	if File_stock_stock_msg_proto != nil {
		return
	}
	file_stock_stock_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stock_stock_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetRealTimeDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetRealTimeDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetIntradayChartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetIntradayChartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetBasicInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetBasicInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetOperatingSnapshotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_stock_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockGetOperatingSnapshotResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_stock_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_stock_msg_proto_goTypes,
		DependencyIndexes: file_stock_stock_msg_proto_depIdxs,
		MessageInfos:      file_stock_stock_msg_proto_msgTypes,
	}.Build()
	File_stock_stock_msg_proto = out.File
	file_stock_stock_msg_proto_rawDesc = nil
	file_stock_stock_msg_proto_goTypes = nil
	file_stock_stock_msg_proto_depIdxs = nil
}
