// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/user_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type UserSginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stype         SginTyoe               `protobuf:"varint,1,opt,name=stype,proto3,enum=SginTyoe" json:"stype" example:"0"` //@go_tags(`json:"stype" example:"0" description:"登录方式“`) 登录方式
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account" example:"" description:"账号"`            //@go_tags(`json:"account" example:"" description:"账号"`) 账号
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password" example:"" description:"密码"`          //@go_tags(`json:"password" example:"" description:"密码"`) 密码
	Mail          string                 `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail" example:"" description:"邮箱地址"`                  //@go_tags(`json:"mail" example:"" description:"邮箱地址"`) 邮箱地址
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone" example:""`                //@go_tags(`json:"phone" example:"" description:"手机号码“`) 手机号
	Ttoken        string                 `protobuf:"bytes,6,opt,name=ttoken,proto3" json:"ttoken" example:"" description:"第三方token"`              //@go_tags(`json:"ttoken" example:"" description:"第三方token"`) 第三方token
	Vcode         string                 `protobuf:"bytes,7,opt,name=vcode,proto3" json:"vcode" example:"" description:"验证码"`                //@go_tags(`json:"vcode" example:"" description:"验证码"`) 验证码
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name" gorm:"name:50" example:"" description:"用户名"`                 //@go_tags(`gorm:"name:50" json:"name" example:"" description:"用户名"`) 用户名
	Avatar        string                 `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar" gorm:"avatar" example:"" description:"头像连接"`             //@go_tags(`gorm:"avatar" json:"avatar" example:"" description:"头像连接"`) 头像连接
	Language      string                 `protobuf:"bytes,12,opt,name=language,proto3" json:"language" example:"en" description:"语言"`         //@go_tags(`json:"language" example:"en" description:"语言"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSginReq) Reset() {
	*x = UserSginReq{}
	mi := &file_user_user_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginReq) ProtoMessage() {}

func (x *UserSginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginReq.ProtoReflect.Descriptor instead.
func (*UserSginReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{0}
}

func (x *UserSginReq) GetStype() SginTyoe {
	if x != nil {
		return x.Stype
	}
	return SginTyoe_Mail
}

func (x *UserSginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserSginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSginReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserSginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSginReq) GetTtoken() string {
	if x != nil {
		return x.Ttoken
	}
	return ""
}

func (x *UserSginReq) GetVcode() string {
	if x != nil {
		return x.Vcode
	}
	return ""
}

func (x *UserSginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSginReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSginReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UserSginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token" example:"认证token" description:"认证token"` //@go_tags(`json:"token" example:"认证token" description:"认证token"`)
	User          *DBUser                `protobuf:"bytes,2,opt,name=user,proto3" json:"user" description:"用户信息"`   //@go_tags(`json:"user" description:"用户信息"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSginResp) Reset() {
	*x = UserSginResp{}
	mi := &file_user_user_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginResp) ProtoMessage() {}

func (x *UserSginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginResp.ProtoReflect.Descriptor instead.
func (*UserSginResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{1}
}

func (x *UserSginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSginResp) GetUser() *DBUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_user_msg_proto protoreflect.FileDescriptor

const file_user_user_msg_proto_rawDesc = "" +
	"\n" +
	"\x13user/user_msg.proto\x1a\x12user/user_db.proto\"\x84\x02\n" +
	"\vUserSginReq\x12\x1f\n" +
	"\x05stype\x18\x01 \x01(\x0e2\t.SginTyoeR\x05stype\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04mail\x18\x04 \x01(\tR\x04mail\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06ttoken\x18\x06 \x01(\tR\x06ttoken\x12\x14\n" +
	"\x05vcode\x18\a \x01(\tR\x05vcode\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\v \x01(\tR\x06avatar\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\"A\n" +
	"\fUserSginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\x04user\x18\x02 \x01(\v2\a.DBUserR\x04userB\x06Z\x04.;pbb\x06proto3"

var (
	file_user_user_msg_proto_rawDescOnce sync.Once
	file_user_user_msg_proto_rawDescData []byte
)

func file_user_user_msg_proto_rawDescGZIP() []byte {
	file_user_user_msg_proto_rawDescOnce.Do(func() {
		file_user_user_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_msg_proto_rawDesc), len(file_user_user_msg_proto_rawDesc)))
	})
	return file_user_user_msg_proto_rawDescData
}

var file_user_user_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_user_msg_proto_goTypes = []any{
	(*UserSginReq)(nil),  // 0: UserSginReq
	(*UserSginResp)(nil), // 1: UserSginResp
	(SginTyoe)(0),        // 2: SginTyoe
	(*DBUser)(nil),       // 3: DBUser
}
var file_user_user_msg_proto_depIdxs = []int32{
	2, // 0: UserSginReq.stype:type_name -> SginTyoe
	3, // 1: UserSginResp.user:type_name -> DBUser
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_user_msg_proto_init() }
func file_user_user_msg_proto_init() {
	if File_user_user_msg_proto != nil {
		return
	}
	file_user_user_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_msg_proto_rawDesc), len(file_user_user_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_msg_proto_goTypes,
		DependencyIndexes: file_user_user_msg_proto_depIdxs,
		MessageInfos:      file_user_user_msg_proto_msgTypes,
	}.Build()
	File_user_user_msg_proto = out.File
	file_user_user_msg_proto_goTypes = nil
	file_user_user_msg_proto_depIdxs = nil
}
