// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/user_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SginTyoe int32

const (
	// 邮箱登录
	// @Description 邮箱登录
	// @example
	SginTyoe_Mail SginTyoe = 0 //手机登录
	// 手机登录
	// @Description 手机登录
	// @example
	SginTyoe_Phone SginTyoe = 1 //手机登录
	// 微信登录
	// @Description 微信登录
	// @example
	SginTyoe_WXChat SginTyoe = 2 //微信登录
	// google登录
	// @Description google登录
	// @example
	SginTyoe_Google SginTyoe = 3 //google登录
	// facebook登录
	// @Description facebook登录
	// @example
	SginTyoe_FaceBook SginTyoe = 4 //facebook登录
	// firebase 登录
	// @Description
	// @example
	SginTyoe_Apple SginTyoe = 5 //Apple 登陆
	// 账号登录
	// @Description 账号登录 账号密码登录
	// @example
	SginTyoe_Account SginTyoe = 6 // 账号登录
	// token登录
	// @Description token登录
	// @example
	SginTyoe_Token SginTyoe = 10 // token登录
)

// Enum value maps for SginTyoe.
var (
	SginTyoe_name = map[int32]string{
		0:  "Mail",
		1:  "Phone",
		2:  "WXChat",
		3:  "Google",
		4:  "FaceBook",
		5:  "Apple",
		6:  "Account",
		10: "Token",
	}
	SginTyoe_value = map[string]int32{
		"Mail":     0,
		"Phone":    1,
		"WXChat":   2,
		"Google":   3,
		"FaceBook": 4,
		"Apple":    5,
		"Account":  6,
		"Token":    10,
	}
)

func (x SginTyoe) Enum() *SginTyoe {
	p := new(SginTyoe)
	*p = x
	return p
}

func (x SginTyoe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SginTyoe) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_db_proto_enumTypes[0].Descriptor()
}

func (SginTyoe) Type() protoreflect.EnumType {
	return &file_user_user_db_proto_enumTypes[0]
}

func (x SginTyoe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SginTyoe.Descriptor instead.
func (SginTyoe) EnumDescriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{0}
}

// 用户数据
type DBUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" gorm:"uid:50;primaryKey"`                        //@go_tags(`gorm:"uid:50;primaryKey" json:"uid"`) 用户ID
	Mail           string                 `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail" gorm:"mail:50;index"`                      //@go_tags(`gorm:"mail:50;index" json:"mail"`) 邮箱
	Phone          string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone" gorm:"phone:50;index"`                    //@go_tags(`gorm:"phone:50;index" json:"phone"`) 手机号
	Name           string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name" gorm:"name:50"`                      //@go_tags(`gorm:"name:50" json:"name"`) 用户名
	Avatar         string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar" gorm:"avatar"`                  //@go_tags(`gorm:"avatar" json:"avatar"`) 玩家头像
	Account        string                 `protobuf:"bytes,12,opt,name=account,proto3" json:"account" gorm:"account:50;index"`               //@go_tags(`gorm:"account:50;index" json:"account"`) 登录帐号
	Password       string                 `protobuf:"bytes,13,opt,name=password,proto3" json:"password"`             //@go_tags(`json:"password"`) 密码登录
	Createtime     int64                  `protobuf:"varint,14,opt,name=createtime,proto3" json:"createtime" gorm:"createtime"`        //@go_tags(`gorm:"createtime" json:"createtime"`) 注册时间
	Language       string                 `protobuf:"bytes,15,opt,name=language,proto3" json:"language" gorm:"language"`             //@go_tags(`gorm:"language" json:"language"`) 语言
	Servicetag     string                 `protobuf:"bytes,16,opt,name=servicetag,proto3" json:"servicetag" gorm:"servicetag"`         //@go_tags(`gorm:"servicetag" json:"servicetag"`) 服务所属区
	Wxopenid       string                 `protobuf:"bytes,17,opt,name=wxopenid,proto3" json:"wxopenid" gorm:"wxopenid:50;index"`             //@go_tags(`gorm:"wxopenid:50;index" json:"wxopenid"`) 微信openid
	Googleopenid   string                 `protobuf:"bytes,18,opt,name=googleopenid,proto3" json:"googleopenid" gorm:"googleopenid:50;index"`     //@go_tags(`gorm:"googleopenid:50;index" json:"googleopenid"`) 谷歌openid
	Facebookopenid string                 `protobuf:"bytes,19,opt,name=facebookopenid,proto3" json:"facebookopenid" gorm:"facebookopenid:50;index"` //@go_tags(`gorm:"facebookopenid:50;index" json:"facebookopenid"`) FaceBook
	Appleopenid    string                 `protobuf:"bytes,20,opt,name=appleopenid,proto3" json:"appleopenid" gorm:"appleopenid:50;index"`       //@go_tags(`gorm:"appleopenid:50;index" json:"appleopenid"`)
	Lastsgintime   int64                  `protobuf:"varint,21,opt,name=lastsgintime,proto3" json:"lastsgintime" gorm:"lastsgintime"`    //@go_tags(`gorm:"lastsgintime" json:"lastsgintime"`) 最后登录时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DBUser) Reset() {
	*x = DBUser{}
	mi := &file_user_user_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUser) ProtoMessage() {}

func (x *DBUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUser.ProtoReflect.Descriptor instead.
func (*DBUser) Descriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUser) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *DBUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DBUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DBUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DBUser) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

func (x *DBUser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DBUser) GetServicetag() string {
	if x != nil {
		return x.Servicetag
	}
	return ""
}

func (x *DBUser) GetWxopenid() string {
	if x != nil {
		return x.Wxopenid
	}
	return ""
}

func (x *DBUser) GetGoogleopenid() string {
	if x != nil {
		return x.Googleopenid
	}
	return ""
}

func (x *DBUser) GetFacebookopenid() string {
	if x != nil {
		return x.Facebookopenid
	}
	return ""
}

func (x *DBUser) GetAppleopenid() string {
	if x != nil {
		return x.Appleopenid
	}
	return ""
}

func (x *DBUser) GetLastsgintime() int64 {
	if x != nil {
		return x.Lastsgintime
	}
	return 0
}

type DBUserStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"id:50;primaryKey;autoIncrement"`               //@go_tags(`gorm:"id:50;primaryKey;autoIncrement" json:"id"`) 主键ID
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" gorm:"uid:50;index"`              //@go_tags(`gorm:"uid:50;index" json:"uid"`) 用户ID
	Stockid       string                 `protobuf:"bytes,3,opt,name=stockid,proto3" json:"stockid" gorm:"stockid:50;index"`      //@go_tags(`gorm:"stockid:50;index" json:"stockid"`) 股票ID
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount" gorm:"amount"`       //@go_tags(`gorm:"amount" json:"amount"`) 股票数量
	Costprice     int32                  `protobuf:"varint,5,opt,name=costprice,proto3" json:"costprice" gorm:"costprice"` //@go_tags(`gorm:"costprice" json:"costprice"`) 成本价
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBUserStock) Reset() {
	*x = DBUserStock{}
	mi := &file_user_user_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUserStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUserStock) ProtoMessage() {}

func (x *DBUserStock) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUserStock.ProtoReflect.Descriptor instead.
func (*DBUserStock) Descriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBUserStock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBUserStock) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUserStock) GetStockid() string {
	if x != nil {
		return x.Stockid
	}
	return ""
}

func (x *DBUserStock) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBUserStock) GetCostprice() int32 {
	if x != nil {
		return x.Costprice
	}
	return 0
}

var File_user_user_db_proto protoreflect.FileDescriptor

const file_user_user_db_proto_rawDesc = "" +
	"\n" +
	"\x12user/user_db.proto\"\xb0\x03\n" +
	"\x06DBUser\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04mail\x18\x02 \x01(\tR\x04mail\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x18\n" +
	"\aaccount\x18\f \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\r \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"createtime\x18\x0e \x01(\x03R\n" +
	"createtime\x12\x1a\n" +
	"\blanguage\x18\x0f \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"servicetag\x18\x10 \x01(\tR\n" +
	"servicetag\x12\x1a\n" +
	"\bwxopenid\x18\x11 \x01(\tR\bwxopenid\x12\"\n" +
	"\fgoogleopenid\x18\x12 \x01(\tR\fgoogleopenid\x12&\n" +
	"\x0efacebookopenid\x18\x13 \x01(\tR\x0efacebookopenid\x12 \n" +
	"\vappleopenid\x18\x14 \x01(\tR\vappleopenid\x12\"\n" +
	"\flastsgintime\x18\x15 \x01(\x03R\flastsgintime\"\x7f\n" +
	"\vDBUserStock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x18\n" +
	"\astockid\x18\x03 \x01(\tR\astockid\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1c\n" +
	"\tcostprice\x18\x05 \x01(\x05R\tcostprice*h\n" +
	"\bSginTyoe\x12\b\n" +
	"\x04Mail\x10\x00\x12\t\n" +
	"\x05Phone\x10\x01\x12\n" +
	"\n" +
	"\x06WXChat\x10\x02\x12\n" +
	"\n" +
	"\x06Google\x10\x03\x12\f\n" +
	"\bFaceBook\x10\x04\x12\t\n" +
	"\x05Apple\x10\x05\x12\v\n" +
	"\aAccount\x10\x06\x12\t\n" +
	"\x05Token\x10\n" +
	"B\x06Z\x04.;pbb\x06proto3"

var (
	file_user_user_db_proto_rawDescOnce sync.Once
	file_user_user_db_proto_rawDescData []byte
)

func file_user_user_db_proto_rawDescGZIP() []byte {
	file_user_user_db_proto_rawDescOnce.Do(func() {
		file_user_user_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_db_proto_rawDesc), len(file_user_user_db_proto_rawDesc)))
	})
	return file_user_user_db_proto_rawDescData
}

var file_user_user_db_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_user_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_user_db_proto_goTypes = []any{
	(SginTyoe)(0),       // 0: SginTyoe
	(*DBUser)(nil),      // 1: DBUser
	(*DBUserStock)(nil), // 2: DBUserStock
}
var file_user_user_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_db_proto_init() }
func file_user_user_db_proto_init() {
	if File_user_user_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_db_proto_rawDesc), len(file_user_user_db_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_db_proto_goTypes,
		DependencyIndexes: file_user_user_db_proto_depIdxs,
		EnumInfos:         file_user_user_db_proto_enumTypes,
		MessageInfos:      file_user_user_db_proto_msgTypes,
	}.Build()
	File_user_user_db_proto = out.File
	file_user_user_db_proto_goTypes = nil
	file_user_user_db_proto_depIdxs = nil
}
