// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: user/user_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SginTyoe int32

const (
	// 邮箱登录
	// @Description 邮箱登录
	// @example
	SginTyoe_Mail SginTyoe = 0 //手机登录
	// 手机登录
	// @Description 手机登录
	// @example
	SginTyoe_Phone SginTyoe = 1 //手机登录
	// 微信登录
	// @Description 微信登录
	// @example
	SginTyoe_WXChat SginTyoe = 2 //微信登录
	// google登录
	// @Description google登录
	// @example
	SginTyoe_Google SginTyoe = 3 //google登录
	// facebook登录
	// @Description facebook登录
	// @example
	SginTyoe_FaceBook SginTyoe = 4 //facebook登录
	// firebase 登录
	// @Description
	// @example
	SginTyoe_Apple SginTyoe = 5 //Apple 登陆
	// 账号登录
	// @Description 账号登录 账号密码登录
	// @example
	SginTyoe_Account SginTyoe = 6 // 账号登录
	// token登录
	// @Description token登录
	// @example
	SginTyoe_Token SginTyoe = 10 // token登录
)

// Enum value maps for SginTyoe.
var (
	SginTyoe_name = map[int32]string{
		0:  "Mail",
		1:  "Phone",
		2:  "WXChat",
		3:  "Google",
		4:  "FaceBook",
		5:  "Apple",
		6:  "Account",
		10: "Token",
	}
	SginTyoe_value = map[string]int32{
		"Mail":     0,
		"Phone":    1,
		"WXChat":   2,
		"Google":   3,
		"FaceBook": 4,
		"Apple":    5,
		"Account":  6,
		"Token":    10,
	}
)

func (x SginTyoe) Enum() *SginTyoe {
	p := new(SginTyoe)
	*p = x
	return p
}

func (x SginTyoe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SginTyoe) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_db_proto_enumTypes[0].Descriptor()
}

func (SginTyoe) Type() protoreflect.EnumType {
	return &file_user_user_db_proto_enumTypes[0]
}

func (x SginTyoe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SginTyoe.Descriptor instead.
func (SginTyoe) EnumDescriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{0}
}

//用户数据
type DBUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid            string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" gorm:"uid:50;primaryKey"`                              //用户ID
	Mail           string `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail" gorm:"mail:50;index"`                                //邮箱
	Phone          string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone" gorm:"phone:50;index"`                             //手机号
	Name           string `protobuf:"bytes,5,opt,name=name,proto3" json:"name" gorm:"name:50"`                                      //用户名
	Avatar         string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar" gorm:"avatar"`                                   //玩家头像
	Account        string `protobuf:"bytes,12,opt,name=account,proto3" json:"account" gorm:"account:50;index"`                      //登录帐号
	Password       string `protobuf:"bytes,13,opt,name=password,proto3" json:"password"`                                            //密码登录
	Createtime     int64  `protobuf:"varint,14,opt,name=createtime,proto3" json:"createtime" gorm:"createtime"`                     //注册时间
	Language       string `protobuf:"bytes,15,opt,name=language,proto3" json:"language" gorm:"language"`                            //语言
	Servicetag     string `protobuf:"bytes,16,opt,name=servicetag,proto3" json:"servicetag" gorm:"servicetag"`                      //服务所属区
	Wxopenid       string `protobuf:"bytes,17,opt,name=wxopenid,proto3" json:"wxopenid" gorm:"wxopenid:50;index"`                   //微信openid
	Googleopenid   string `protobuf:"bytes,18,opt,name=googleopenid,proto3" json:"googleopenid" gorm:"googleopenid:50;index"`       //谷歌openid
	Facebookopenid string `protobuf:"bytes,19,opt,name=facebookopenid,proto3" json:"facebookopenid" gorm:"facebookopenid:50;index"` //FaceBook
	Appleopenid    string `protobuf:"bytes,20,opt,name=appleopenid,proto3" json:"appleopenid" gorm:"appleopenid:50;index"`          //
	Lastsgintime   int64  `protobuf:"varint,21,opt,name=lastsgintime,proto3" json:"lastsgintime" gorm:"lastsgintime"`               //最后登录时间
}

func (x *DBUser) Reset() {
	*x = DBUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUser) ProtoMessage() {}

func (x *DBUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUser.ProtoReflect.Descriptor instead.
func (*DBUser) Descriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUser) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *DBUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DBUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DBUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DBUser) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

func (x *DBUser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DBUser) GetServicetag() string {
	if x != nil {
		return x.Servicetag
	}
	return ""
}

func (x *DBUser) GetWxopenid() string {
	if x != nil {
		return x.Wxopenid
	}
	return ""
}

func (x *DBUser) GetGoogleopenid() string {
	if x != nil {
		return x.Googleopenid
	}
	return ""
}

func (x *DBUser) GetFacebookopenid() string {
	if x != nil {
		return x.Facebookopenid
	}
	return ""
}

func (x *DBUser) GetAppleopenid() string {
	if x != nil {
		return x.Appleopenid
	}
	return ""
}

func (x *DBUser) GetLastsgintime() int64 {
	if x != nil {
		return x.Lastsgintime
	}
	return 0
}

type DBUserStock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"id:50;primaryKey;autoIncrement"` //主键ID
	Uid       string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" gorm:"uid:50;index"`                  //用户ID
	Stockid   string `protobuf:"bytes,3,opt,name=stockid,proto3" json:"stockid" gorm:"stockid:50;index"`      //股票ID
	Amount    int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount" gorm:"amount"`                 //股票数量
	Costprice int32  `protobuf:"varint,5,opt,name=costprice,proto3" json:"costprice" gorm:"costprice"`        //成本价
}

func (x *DBUserStock) Reset() {
	*x = DBUserStock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBUserStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUserStock) ProtoMessage() {}

func (x *DBUserStock) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUserStock.ProtoReflect.Descriptor instead.
func (*DBUserStock) Descriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBUserStock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBUserStock) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUserStock) GetStockid() string {
	if x != nil {
		return x.Stockid
	}
	return ""
}

func (x *DBUserStock) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBUserStock) GetCostprice() int32 {
	if x != nil {
		return x.Costprice
	}
	return 0
}

var File_user_user_db_proto protoreflect.FileDescriptor

var file_user_user_db_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x03, 0x0a, 0x06, 0x44, 0x42, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x74, 0x61, 0x67, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x74, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x78, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x78, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x61, 0x63,
	0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x73, 0x67, 0x69, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x73,
	0x67, 0x69, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x0b, 0x44, 0x42, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x73, 0x74, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63,
	0x6f, 0x73, 0x74, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2a, 0x68, 0x0a, 0x08, 0x53, 0x67, 0x69, 0x6e,
	0x54, 0x79, 0x6f, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x58, 0x43,
	0x68, 0x61, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10,
	0x03, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x10, 0x04, 0x12,
	0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x10, 0x0a, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_user_user_db_proto_rawDescOnce sync.Once
	file_user_user_db_proto_rawDescData = file_user_user_db_proto_rawDesc
)

func file_user_user_db_proto_rawDescGZIP() []byte {
	file_user_user_db_proto_rawDescOnce.Do(func() {
		file_user_user_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_user_db_proto_rawDescData)
	})
	return file_user_user_db_proto_rawDescData
}

var file_user_user_db_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_user_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_user_db_proto_goTypes = []interface{}{
	(SginTyoe)(0),       // 0: SginTyoe
	(*DBUser)(nil),      // 1: DBUser
	(*DBUserStock)(nil), // 2: DBUserStock
}
var file_user_user_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_db_proto_init() }
func file_user_user_db_proto_init() {
	if File_user_user_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_user_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBUserStock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_user_db_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_db_proto_goTypes,
		DependencyIndexes: file_user_user_db_proto_depIdxs,
		EnumInfos:         file_user_user_db_proto_enumTypes,
		MessageInfos:      file_user_user_db_proto_msgTypes,
	}.Build()
	File_user_user_db_proto = out.File
	file_user_user_db_proto_rawDesc = nil
	file_user_user_db_proto_goTypes = nil
	file_user_user_db_proto_depIdxs = nil
}
