// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: user/user_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//登录请求
type UserSginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stype    SginTyoe `protobuf:"varint,1,opt,name=stype,proto3,enum=SginTyoe" json:"stype" example:"0" description:"登录方式“"` //登录方式
	Account  string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account" example:"" description:"账号"`                //账号
	Password string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password" example:"" description:"密码"`              //密码
	Mail     string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail" example:"" description:"邮箱地址"`                    //邮箱地址
	Phone    string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone" description:"手机号码“" example:""`                 //手机号
	Ttoken   string   `protobuf:"bytes,6,opt,name=ttoken,proto3" json:"ttoken" example:"" description:"第三方token"`            //第三方token
	Vcode    string   `protobuf:"bytes,7,opt,name=vcode,proto3" json:"vcode" example:"" description:"验证码"`                   //验证码
	Name     string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name" description:"用户名" gorm:"name:50" example:""`     //用户名
	Avatar   string   `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar" gorm:"avatar" example:"" description:"头像连接"` //头像连接
	Language string   `protobuf:"bytes,12,opt,name=language,proto3" json:"language" example:"en" description:"语言"`           //
}

func (x *UserSginReq) Reset() {
	*x = UserSginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginReq) ProtoMessage() {}

func (x *UserSginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginReq.ProtoReflect.Descriptor instead.
func (*UserSginReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{0}
}

func (x *UserSginReq) GetStype() SginTyoe {
	if x != nil {
		return x.Stype
	}
	return SginTyoe_Mail
}

func (x *UserSginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserSginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSginReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserSginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSginReq) GetTtoken() string {
	if x != nil {
		return x.Ttoken
	}
	return ""
}

func (x *UserSginReq) GetVcode() string {
	if x != nil {
		return x.Vcode
	}
	return ""
}

func (x *UserSginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSginReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSginReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UserSginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token" example:"认证token" description:"认证token"`
	User  *DBUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user" description:"用户信息"`
}

func (x *UserSginResp) Reset() {
	*x = UserSginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginResp) ProtoMessage() {}

func (x *UserSginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginResp.ProtoReflect.Descriptor instead.
func (*UserSginResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{1}
}

func (x *UserSginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSginResp) GetUser() *DBUser {
	if x != nil {
		return x.User
	}
	return nil
}

//获取用户股票信息请求
type UserGetStocksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetStocksReq) Reset() {
	*x = UserGetStocksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetStocksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetStocksReq) ProtoMessage() {}

func (x *UserGetStocksReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetStocksReq.ProtoReflect.Descriptor instead.
func (*UserGetStocksReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{2}
}

type UserGetStocksResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stocks []*DBUserStock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks" description:"用户股票信息"` //用户股票信息
}

func (x *UserGetStocksResp) Reset() {
	*x = UserGetStocksResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetStocksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetStocksResp) ProtoMessage() {}

func (x *UserGetStocksResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetStocksResp.ProtoReflect.Descriptor instead.
func (*UserGetStocksResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{3}
}

func (x *UserGetStocksResp) GetStocks() []*DBUserStock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

//添加用户股票信息请求
type UserAddStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock *DBUserStock `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock" description:"用户股票信息"` //用户股票信息
}

func (x *UserAddStockReq) Reset() {
	*x = UserAddStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAddStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddStockReq) ProtoMessage() {}

func (x *UserAddStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddStockReq.ProtoReflect.Descriptor instead.
func (*UserAddStockReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{4}
}

func (x *UserAddStockReq) GetStock() *DBUserStock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type UserAddStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock *DBUserStock `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock" description:"用户股票信息"` //用户股票信息
}

func (x *UserAddStockResp) Reset() {
	*x = UserAddStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAddStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddStockResp) ProtoMessage() {}

func (x *UserAddStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddStockResp.ProtoReflect.Descriptor instead.
func (*UserAddStockResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{5}
}

func (x *UserAddStockResp) GetStock() *DBUserStock {
	if x != nil {
		return x.Stock
	}
	return nil
}

//删除用户股票信息请求
type UserDelStockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stockid []string `protobuf:"bytes,2,rep,name=stockid,proto3" json:"stockid" description:"股票ID" example:""` //股票ID
}

func (x *UserDelStockReq) Reset() {
	*x = UserDelStockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDelStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelStockReq) ProtoMessage() {}

func (x *UserDelStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelStockReq.ProtoReflect.Descriptor instead.
func (*UserDelStockReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{6}
}

func (x *UserDelStockReq) GetStockid() []string {
	if x != nil {
		return x.Stockid
	}
	return nil
}

type UserDelStockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserDelStockResp) Reset() {
	*x = UserDelStockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDelStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelStockResp) ProtoMessage() {}

func (x *UserDelStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelStockResp.ProtoReflect.Descriptor instead.
func (*UserDelStockResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{7}
}

var File_user_user_msg_proto protoreflect.FileDescriptor

var file_user_user_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x02, 0x0a, 0x0b, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x53, 0x67, 0x69, 0x6e, 0x54,
	0x79, 0x6f, 0x65, 0x52, 0x05, 0x73, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x22, 0x41, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x42, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x22, 0x39, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44,
	0x42, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x42, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x36, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44,
	0x42, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x22, 0x2b, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x69, 0x64, 0x22, 0x12,
	0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_user_user_msg_proto_rawDescOnce sync.Once
	file_user_user_msg_proto_rawDescData = file_user_user_msg_proto_rawDesc
)

func file_user_user_msg_proto_rawDescGZIP() []byte {
	file_user_user_msg_proto_rawDescOnce.Do(func() {
		file_user_user_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_user_msg_proto_rawDescData)
	})
	return file_user_user_msg_proto_rawDescData
}

var file_user_user_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_user_msg_proto_goTypes = []interface{}{
	(*UserSginReq)(nil),       // 0: UserSginReq
	(*UserSginResp)(nil),      // 1: UserSginResp
	(*UserGetStocksReq)(nil),  // 2: UserGetStocksReq
	(*UserGetStocksResp)(nil), // 3: UserGetStocksResp
	(*UserAddStockReq)(nil),   // 4: UserAddStockReq
	(*UserAddStockResp)(nil),  // 5: UserAddStockResp
	(*UserDelStockReq)(nil),   // 6: UserDelStockReq
	(*UserDelStockResp)(nil),  // 7: UserDelStockResp
	(SginTyoe)(0),             // 8: SginTyoe
	(*DBUser)(nil),            // 9: DBUser
	(*DBUserStock)(nil),       // 10: DBUserStock
}
var file_user_user_msg_proto_depIdxs = []int32{
	8,  // 0: UserSginReq.stype:type_name -> SginTyoe
	9,  // 1: UserSginResp.user:type_name -> DBUser
	10, // 2: UserGetStocksResp.stocks:type_name -> DBUserStock
	10, // 3: UserAddStockReq.stock:type_name -> DBUserStock
	10, // 4: UserAddStockResp.stock:type_name -> DBUserStock
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_user_msg_proto_init() }
func file_user_user_msg_proto_init() {
	if File_user_user_msg_proto != nil {
		return
	}
	file_user_user_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_user_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetStocksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetStocksResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAddStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAddStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDelStockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDelStockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_user_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_msg_proto_goTypes,
		DependencyIndexes: file_user_user_msg_proto_depIdxs,
		MessageInfos:      file_user_user_msg_proto_msgTypes,
	}.Build()
	File_user_user_msg_proto = out.File
	file_user_user_msg_proto_rawDesc = nil
	file_user_user_msg_proto_goTypes = nil
	file_user_user_msg_proto_depIdxs = nil
}
